### DISCUSSION TITLE
Allow referencing security groups by names in SecurityGroupPolicy resource

### DISCUSSION THREAD

**Discussion by vgrigoruk** [aws/amazon-vpc-cni-k8s#2249] [Ideas]
AWS ALB controller supports specifying security groups via ID (e.g. sg-XXXXXX) and name: https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.2/guide/ingress/annotations/#security-groups

> Both name or ID of securityGroups are supported. Name matches a Name tag, not the groupName attribute.

According to [documentation](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html), `SecurityGroupPolicy` supports `securityGroupIds` only. 
It will be very convenient to support specifying security groups by name too, as it would allow us to generate / template `SecurityGroupPolicy` resource w/o explicitly passing a specific security group IDs (which are usually managed separately with other IaaC tools, e.g. Terraform).

Example:

```
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: my-security-group-policy
  namespace: my-namespace
spec:
  podSelector: 
    matchLabels:
      role: my-role
  securityGroups:
    groupIds:
    - my_pod_security_group_id
    groupNames:
      - pod_security_group_name_tag
```
