### ISSUE TITLE
setting AWS_VPC_K8S_CNI_EXTERNALSNAT=false adds latency

### ISSUE THREAD

**Issue by bhaveshph** [aws/amazon-vpc-cni-k8s#1087]
EKS / k8s version : 1.16
aws-vpc-cni version : 1.6.1
calico version (using this only for network policy) : 3.8.1 
iptables --version => iptables v1.8.2 (legacy)

Following has been noticed with using Primary IP range and also Secondary IP range (where, AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true) for pods.

- setting AWS_VPC_K8S_CNI_EXTERNALSNAT=false (will use iptable rule to SNAT)
  egress calls to peered vpc, take 0.300 ms, as per 'traceroute -T -p 443 app1-dns'

- setting AWS_VPC_K8S_CNI_EXTERNALSNAT=true (will not use iptable rule to SNAT)
  egress calls to peered vpc, takes 0.019 ms, as per 'traceroute -T -p 443 app1-dns'

I also tried setting, AWS_VPC_K8S_CNI_RANDOMIZESNAT=prng. iptables rules are added fine (without node reboot) and seems to be working correctly; But latency remains same as mentioned above.

Has anyone seen this before?
Am I missing something ?
Is it outstanding issue where SNATing with iptable from ec2 node adds up to latency ?

**Comment by mogren** [comment]
Hi @bhaveshph, 

If you have a peered VPC, you can set `AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS` (see [Readme](https://github.com/aws/amazon-vpc-cni-k8s#cni-configuration-variables)) with the CIDRs you want to avoid SNAT for. See #53 for some background on this issue. 

I'm not sure where the increased latency comes from though, it used to not work at all with peered VPCs if SNAT was enabled, so it is possible that using SNAT triggers some alternate routing that adds additional latency. This blog post on the subject is pretty good: https://kubernetes.io/blog/2019/03/29/kube-proxy-subtleties-debugging-an-intermittent-connection-reset/

**Comment by bhaveshph** [comment]
Hi @mogren 

I see, https://github.com/awslabs/amazon-eks-ami/issues/505
and upgraded EKS from 1.16 to 1.17 and using kube-proxy 1.17.7. 
so prng option works, make --fully-random and iptables version is good and kube-proxy also happy.

I try following options for cni and still latency remains same.

```
env:
  AWS_VPC_K8S_CNI_LOGLEVEL: DEBUG
  AWS_VPC_K8S_CNI_VETHPREFIX: eni
  AWS_VPC_ENI_MTU: "9001"
  AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG: true
  ENI_CONFIG_LABEL_DEF: failure-domain.beta.kubernetes.io/zone
  AWS_VPC_K8S_CNI_EXTERNALSNAT: false
  AWS_VPC_K8S_CNI_RANDOMIZESNAT: prng
  AWS_VPC_K8S_CNI_EXCLUDE_SNAT_CIDRS: 100.67.0.0/16
```
