### ISSUE TITLE
Default security group attached when no others declared

### ISSUE THREAD

**Issue by edward2a** [aws/amazon-vpc-cni-k8s#1124]
Following documentation here:
- https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html

This leads to believe that the SG behaviour is consistent in the sense that, if no SG's are declared when adding subnets, the same SG's will be used as the primary interface.
The actual behaviour is that ENIs created in the added subnet will have attachment to the VPC's default SG instead.
I believe this should not be the case and rather, by default, use the same SG's as the primary interface.

```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-west-2a
spec: 
  subnet: subnet-011b111c1f11fdf11
```
The code above results in ENIs with VPC's default SG.
Applying this configuration should either 'use the primary iface SGs' or 'fail to apply'.

Thank you,
Ed
