### ISSUE TITLE
ENI Config Label/Annotation Def Concatenation

### ISSUE THREAD

**Issue by tanguyfalconnet** [aws/amazon-vpc-cni-k8s#1207]
**What would you like to be added**:
Currently, with Custom Networking, VPC CNI can easily use one subnet and security group per AZ when reading `failure-domain.beta.kubernetes.io/zone` label. But if we want to use multiple custom network per AZ, we can't rely on only one label. We should be able to concanate labels/annotations in `ENI_CONFIG_LABEL_DEF` and `ENI_CONFIG_ANNOTATION_DEF`.

Example of ENIConfig with 3 subnets :
name : eu-west-1a, subnet : 10.0.0.0/18
name : eu-west-1b, subnet : 10.0.64.0/18
name : eu-west-1c, subnet : 10.0.128.0/18
ENI_CONFIG_LABEL_DEF = `failure-domain.beta.kubernetes.io/zone`

Example of ENIConfig with 6 subnets :
name : sub1-eu-west-1a, subnet : 10.0.0.0/18
name : sub1-eu-west-1b, subnet : 10.0.64.0/18
name : sub1-eu-west-1c, subnet : 10.0.128.0/18
name : sub2-eu-west-1a, subnet : 10.1.0.0/18
name : sub2-eu-west-1b, subnet : 10.1.64.0/18
name : sub2-eu-west-1c, subnet : 10.1.128.0/18
ENI_CONFIG_LABEL_DEF = `some_label_containing_sub_name,failure-domain.beta.kubernetes.io/zone`

**Why is this needed**:
We would like to be able to use more IPs than provided by three `/18` subnets for our pods.

**Comment by prabhushan** [comment]
This is really needed.. Can anyone check the status of this one?

**Comment by jayanthvn** [comment]
Hi,

Sure I can discuss internally and we will prioritize this, so instead of sub1-eu-west-1a and sub2-eu-west-1a would it be fine if we have list of subnets something like - 

```
cat <<EOF | kubectl apply -f -
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: $AZ2
spec:
  securityGroups: 
    - sg-xxxxxxxxxxxx
  subnet: 
    - $CUST_SNET1
    - $CUST_SNET2
EOF
```
