### ISSUE TITLE
Pod Network Policies with vpc-cni

### ISSUE THREAD

**Issue by tirumerla** [aws/amazon-vpc-cni-k8s#1257]
**What happened**:

I have applied pod network policies for all of my namespaces and individual pods. None of them have impact on restricting the traffic, even though i blocked egress to all traffic except to specific IP i still can access the internet ( eg. amazon.com, google.com etc.. ) from the individual pods. I was wondering if vpc-cni ( aws-node daemon set ) is enough to enforce network policies or do i need calico to enforce these network policies.

Here's the example policy i have 
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: jupyternotebook
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: jupyternotebook-access
  namespace: jupyternotebook
spec:
  podSelector: 
    matchLabels:
      app: jupyternotebook
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - ports:
        - port: 443
          protocol: TCP
      from:
        - namespaceSelector:
            matchLabels:
              namespace: traefik
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: traefik
              app.kubernetes.io/managed-by: Helm
              app.kubernetes.io/name: traefik
              helm.sh/chart: traefik-9.1.1
  egress:
    - to:
        - ipBlock:
            cidr: <dest_ip>/32
      ports:
        - port: 4000
          protocol: TCP
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
```
Appreciate your help. Thanks.

**Environment**:
- Kubernetes version (use `kubectl version`): `EKS - v1.17.9`
- CNI Version: `v1.6.3`
- OS (e.g: `cat /etc/os-release`): `Amazon Linux 2`
- Kernel (e.g. `uname -a`): `Linux  4.14.193-149.317.amzn2.x86_64 #1 SMP x86_64 GNU/Linux`
