### ISSUE TITLE
Error: "OPERATOR_NAME must be set" after enabling custom networking

### ISSUE THREAD

**Issue by ranimufid** [aws/amazon-vpc-cni-k8s#1283]
**What happened**:

I recently added a secondary IPv4 CIDR range to the VPC associated with my EKS cluster. After enabling custom networking using vpc-cni I started receiving the following error message on pod start up 

```
time="2020-11-05T14:32:06Z" level=error msg="failed to initialize service object for operator metrics: OPERATOR_NAME must be set"
```

I enabled custom networking by setting the following:
```
AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG = true
ENI_CONFIG_LABEL_DEF = true
```

The allocation of IPs from the secondary range to pods is working fine and as expected, I am just wondering if the above error is acceptable or if it has some undesired consequences.

**Environment**:
- Kubernetes version: `v1.16.13-eks`

- CNI Version: `v1.7.5`
- OS: `Amazon Linux 2`
- Kernel
```
Linux <hostname> 4.14.193-149.317.amzn2.x86_64
```

**Comment by jayanthvn** [comment]
Hi @ranimufid 

Did you follow the steps from here - https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html ?

Also why is `ENI_CONFIG_LABEL_DEF set to true`? I think you are missing `failure-domain.beta.kubernetes.io/zone label`. 

Please try setting this -
```
kubectl set env daemonset aws-node -n kube-system ENI_CONFIG_LABEL_DEF=failure-domain.beta.kubernetes.io/zone
```

Thanks, hope this help.

**Comment by ranimufid** [comment]
@jayanthvn apologies, I made a mistake when copying and pasting from my editor. What I meant to share initially is that I have both of the following set as required! And yes, I have followed the instructions mentioned in the guide you shared. 

```
AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG = true
ENI_CONFIG_LABEL_DEF = failure-domain.beta.kubernetes.io/zone
```

The only step mentioned in the guide that I have omitted is the following which as per what I understand is unnecessary if `ENI_CONFIG_LABEL_DEF` is defined

```
kubectl annotate node <node-name>.<region>.compute.internal k8s.amazonaws.com/eniConfig=<subnet1ConfigName>
```

**Comment by jayanthvn** [comment]
Thanks for confirming. I generally follow the steps here - https://aws.amazon.com/premiumsupport/knowledge-center/eks-multiple-cidr-ranges/ and not seeing the issue. Will dig through more and get back to you.

**Comment by ranimufid** [comment]
Here's both my `CustomResourceDefinition` as well as `ENIConfig`s

```
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  scope: Cluster
  group: crd.k8s.amazonaws.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
  names:
    plural: eniconfigs
    singular: eniconfig
    kind: ENIConfig
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-1a
spec:
  subnet: subnet-0123456789
  securityGroups: 
    - sg-0123456789
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: us-east-1b
spec:
  subnet: subnet-0234567890
  securityGroups: 
    - sg-023456789

```

**Comment by jayanthvn** [comment]
Only difference I am seeing is this - 

```
versions:
    - name: v1alpha1
      served: true
      storage: true
```
When I get a chance will try this CRD and see if I can repro. Will get back to you asap.

Thanks.
