### ISSUE TITLE
hostPort Not Working with Deployments

### ISSUE THREAD

**Issue by brockoffdev** [aws/amazon-vpc-cni-k8s#132]
Issue I've run into with EKS...we launch our Vault containers utilizing a [hostPort](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#containerport-v1-core) for a number of reasons, the biggest being due to our reliance on Proxy Protocol headers and the ELB's health check to balance the standby Vault containers in an HA setup.

Because of this, we need to bring up the containers as follows:

```
      - name: vault
        image: vault:0.10.2
        command:
          - vault
          - server
          - -config=/vault/config/config.hcl
        ports:
        - containerPort: 8200
          hostPort: 8200
          name: vaultport
          protocol: TCP
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: VAULT_API_ADDR
          value: https://[HTTPS Address]
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8200
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8200
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: config-volume
          mountPath: /vault/config/config.hcl
        - name: vault-audit-logs
          mountPath: /vault/log  
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory:  1024Mi
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            add:
              - IPC_LOCK
```

Unfortunately, this does not work, as the hostPort is never created.  Additionally, setting the securityContext to "privileged" also does not work (OS: `Amazon Linux 2`).

Any thoughts on this?  I think it may be related to the EKS VPC CNI, but I'm still trying to debug....
