### ISSUE TITLE
Pod fails to start, when trying to access SecurityGroup in different VPC

### ISSUE THREAD

**Issue by Voigtus** [aws/amazon-vpc-cni-k8s#1361]
**What happened**:

I want to access a RDS Database in a different AWS-Account. Therefore I used the following SecurityGroupPolicy:
```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: sa-sgp
  namespace: test
spec:
  serviceAccountSelector:
    matchLabels:
      role: REMOTE-accessor
  securityGroups:
    groupIds:
      - <cluster-security-group>
      - <remote-account-id>/<remote-security-group-id>
```

The result is my pod is not capable to start anymore and fails with the message:
`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "bcd4af8f09595a54b788a1d2002066d274088f5204abbdcd634a673137cebb05" network for pod "spring-boot-demo-app-8486955796-rm6gc": networkPlugin cni failed to set up pod "spring-boot-demo-app-8486955796-rm6gc_test" network: add cmd: failed to assign an IP address to container`

I guess this happens due to this error message:
`failed to allocate branch ENI to pod: eni wrapper: unable to create network interface: InvalidParameterValue: user <my-account-id> does not own a resource <remote-account-id>/<remote-security-group-id> status code: 400, request id: 345bd2f2-f433-4957-8c92-a6b4d9403878`

Now my question: Is there another way to reference a security group in a remote VPC? Both VPC are in the same region and are peered. I followed [these instructions ](https://docs.aws.amazon.com/vpc/latest/peering/vpc-peering-security-groups.html) and I'm still not able to access the security group in the remote account.

**Environment**:
- Kubernetes version: v1.18.9-eks-d1db3c
- CNI Version: v1.7.5-eksbuild.1
- OS Image: Amazon Linux 2
- Kernel: 4.14.209-160.335.amzn2.x86_64
