### ISSUE TITLE
Existing pod network not cleanedup when using security groups with stateful sets

### ISSUE THREAD

**Issue by hintofbasil** [aws/amazon-vpc-cni-k8s#1374]
**What happened**:
When using security groups with stateful sets we noticed that pods often lost connectivity when restarted.
The security group they were bound to allowed all connections inbound and outbound on 0.0.0.0/0.

After some investigation we discovered the bug seems to affect pods re-created on the same node with the same name.

**Attach logs**
[eks_i-08aff468a2d6ce527_2021-02-05_1421-UTC_0.6.2.tar.gz](https://github.com/aws/amazon-vpc-cni-k8s/files/5933132/eks_i-08aff468a2d6ce527_2021-02-05_1421-UTC_0.6.2.tar.gz)

**What you expected to happen**:

The pod should launch normally

**How to reproduce it (as minimally and precisely as possible)**:

Create a securityGroupPolicy

```yaml
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: cni-test
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: cni-test
  securityGroups:
    groupIds:
      - <id>
```

Create a pod which uses the security group policy

```yaml
kind: Pod
metadata:
  name: cni-test
  namespace: default
  labels:
    app: cni-test
spec:
  containers:
    - name: alpine
      image: alpine
      command:
      - sleep
      - "1000000000"
```

Kill the pod then recreate the pod ensuring it is scheduled to the same node.  Then attempt to make an outbound connection from the pod

```bash
apk add curl
curl 1.1.1.1
```

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

- CNI Version

```
v1.7.5-eksbuild.1
```

- OS (e.g: `cat /etc/os-release`):

```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

- Kernel (e.g. `uname -a`):

```
Linux ip-172-16-214-206.eu-central-1.compute.internal 4.14.209-160.339.amzn2.x86_64 #1 SMP Wed Dec 16 22:44:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
