### ISSUE TITLE
Race Condition when deploying a Helm Chart with SecurityGroupPolicy?

### ISSUE THREAD

**Issue by Skaronator** [aws/amazon-vpc-cni-k8s#1398]
**What happened**:

We're using the new pod security group feature and we noticed across multiple cluster that there seems to be a race condition on the **very first deployment** resulting in the security group doesn't get attached to the pod.

We deploy our services with a helm chart. The helm chart is mostly a default chart generated with `helm create xyz`. We only added a few minor things including a SecurityGroupPolicy Resource that looks like this:

```yaml
{{- if .Values.securityGroups -}}
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: {{ include "generic-service.fullname" . }}
  labels:
    {{- include "generic-service.labels" . | nindent 4 }}
spec:
  podSelector: 
    matchLabels:
      {{- include "generic-service.selectorLabels" . | nindent 6 }}
  securityGroups:
    {{- with .Values.securityGroups }}
    groupIds:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
```

So on the very first deployment the pod starts but the security doesn't seems to be attached. Resulting in the pod not reaching our AWS ElastiCache Redis cluster.

Running kubectl describe on the pod give us the following:

```yaml
$ k -n retracted describe pod auth-component-gatekeeper-854b7f97bb-jvh8k
Name:         auth-component-gatekeeper-854b7f97bb-jvh8k
Namespace:    retracted
Priority:     0
Node:         ip-10-101-15-137.eu-west-1.compute.internal/10.101.15.137
Start Time:   Thu, 04 Mar 2021 17:48:20 +0100
Labels:       app.kubernetes.io/instance=auth-component-gatekeeper
              app.kubernetes.io/name=auth-component-gatekeeper
              pod-template-hash=854b7f97bb
Annotations:  checksum/securityGroups: e35eff4571c65fc63d9887ca82a27c345a05d7f1f73b3b8a3f4e30a1834dbc8e
              kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.101.8.248
IPs:
  IP:           10.101.8.248
Controlled By:  ReplicaSet/auth-component-gatekeeper-854b7f97bb
Containers:
  auth-component-gatekeeper:
    Container ID:   docker://d765b7fa1587c392d06c992ffe21819eea57c686e4c63d564820b1f7335afe3e
    Image:          1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper:main_1614268030
    Image ID:       docker-pullable://1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper@sha256:8082f9591b32581dac4892c8d4132710ef8b48f85b990573ab56fe0415031665
    Ports:          8443/TCP, 15000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 04 Mar 2021 17:48:23 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     750m
      memory:  768Mi
    Requests:
      cpu:      500m
      memory:   768Mi
    Liveness:   http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:    http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=18
    Environment:
      AWS_DEFAULT_REGION:           eu-west-1
      AWS_REGION:                   eu-west-1
      AWS_ROLE_ARN:                 arn:aws:iam::265482181561:role/k8s-pod-retracted-auth-component-gatekeeper
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from auth-component-gatekeeper-token-647t5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  auth-component-gatekeeper-token-647t5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  auth-component-gatekeeper-token-647t5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  58s                default-scheduler  Successfully assigned retracted/auth-component-gatekeeper-854b7f97bb-jvh8k to ip-10-101-15-137.eu-west-1.compute.internal
  Normal   Pulling    58s                kubelet            Pulling image "1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper:main_1614268030"
  Normal   Pulled     55s                kubelet            Successfully pulled image "1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper:main_1614268030" in 2.181899216s
  Normal   Created    55s                kubelet            Created container auth-component-gatekeeper
  Normal   Started    55s                kubelet            Started container auth-component-gatekeeper
  Warning  Unhealthy  31s (x3 over 51s)  kubelet            Startup probe failed: Get "http://10.101.8.248:15000/health": dial tcp 10.101.8.248:15000: connect: connection refused
  Warning  Unhealthy  0s (x3 over 20s)   kubelet            Startup probe failed: Get "http://10.101.8.248:15000/health": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

The pod never get healthy because it cannot reach redis because the security group is not attached properly. Kubernetes will restart the pod but that doesn't fix it. Redis is still not rachable.

We need to delete the pod manually. After doing that the security group is correctly attached.

```
$ k -n retracted delete pod auth-component-gatekeeper-854b7f97bb-jvh8k
```
When doing kubectl describe we can now see that the `vpc.amazonaws.com/pod-eni` is listed in Limits/Requests:

```yaml
$ k -n retracted describe pod auth-component-gatekeeper-854b7f97bb-6f89l
Name:         auth-component-gatekeeper-854b7f97bb-6f89l
Namespace:    retracted
Priority:     0
Node:         ip-10-101-11-22.eu-west-1.compute.internal/10.101.11.22
Start Time:   Thu, 04 Mar 2021 17:50:25 +0100
Labels:       app.kubernetes.io/instance=auth-component-gatekeeper
              app.kubernetes.io/name=auth-component-gatekeeper
              pod-template-hash=854b7f97bb
Annotations:  checksum/securityGroups: e35eff4571c65fc63d9887ca82a27c345a05d7f1f73b3b8a3f4e30a1834dbc8e
              kubernetes.io/psp: eks.privileged
              vpc.amazonaws.com/pod-eni:
                [{"eniId":"eni-0452b320e9a6476bd","ifAddress":"06:5c:9a:b5:ee:63","privateIp":"10.101.6.255","vlanId":1,"subnetCidr":"10.101.0.0/20"}]
Status:       Running
IP:           10.101.6.255
IPs:
  IP:           10.101.6.255
Controlled By:  ReplicaSet/auth-component-gatekeeper-854b7f97bb
Containers:
  auth-component-gatekeeper:
    Container ID:   docker://bfbfa74a2ea4e969614c8037bb4916c704162f20764c4ce1093c729567c53086
    Image:          1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper:main_1614268030
    Image ID:       docker-pullable://1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper@sha256:8082f9591b32581dac4892c8d4132710ef8b48f85b990573ab56fe0415031665
    Ports:          8443/TCP, 15000/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Running
      Started:      Thu, 04 Mar 2021 17:50:27 +0100
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:                        750m
      memory:                     768Mi
      vpc.amazonaws.com/pod-eni:  1
    Requests:
      cpu:                        500m
      memory:                     768Mi
      vpc.amazonaws.com/pod-eni:  1
    Liveness:                     http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Readiness:                    http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Startup:                      http-get http://:metrics/health delay=0s timeout=1s period=10s #success=1 #failure=18
    Environment:
      AWS_DEFAULT_REGION:           eu-west-1
      AWS_REGION:                   eu-west-1
      AWS_ROLE_ARN:                 arn:aws:iam::265482181561:role/k8s-pod-retracted-auth-component-gatekeeper
      AWS_WEB_IDENTITY_TOKEN_FILE:  /var/run/secrets/eks.amazonaws.com/serviceaccount/token
    Mounts:
      /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from auth-component-gatekeeper-token-647t5 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
  auth-component-gatekeeper-token-647t5:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  auth-component-gatekeeper-token-647t5
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
                 vpc.amazonaws.com/pod-eni:NoSchedule op=Exists
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               11s   default-scheduler        Successfully assigned retracted/auth-component-gatekeeper-854b7f97bb-6f89l to ip-10-101-11-22.eu-west-1.compute.internal
  Normal   SecurityGroupRequested  11s   vpc-resource-controller  Pod will get the following Security Groups [sg-0bc8e1b16e3a16581 sg-059464811fcdae091]
  Warning  FailedCreatePodSandBox  10s   kubelet                  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d41a3d72e54d4e16c440c1cd37f73f9ef065c10a6aedee09511579cdde92f842" network for pod "auth-component-gatekeeper-854b7f97bb-6f89l": networkPlugin cni failed to set up pod "auth-component-gatekeeper-854b7f97bb-6f89l_retracted" network: add cmd: failed to assign an IP address to container
  Normal   ResourceAllocated       10s   vpc-resource-controller  Allocated [{"eniId":"eni-0452b320e9a6476bd","ifAddress":"06:5c:9a:b5:ee:63","privateIp":"10.101.6.255","vlanId":1,"subnetCidr":"10.101.0.0/20"}] to the pod
  Normal   SandboxChanged          10s   kubelet                  Pod sandbox changed, it will be killed and re-created.
  Normal   Pulled                  10s   kubelet                  Container image "1234567890123.dkr.ecr.eu-west-1.amazonaws.com/auth-component-gatekeeper:main_1614268030" already present on machine
  Normal   Created                 9s    kubelet                  Created container auth-component-gatekeeper
  Normal   Started                 9s    kubelet                  Started container auth-component-gatekeeper
  Warning  Unhealthy               5s    kubelet                  Startup probe failed: Get "http://10.101.6.255:15000/health": dial tcp 10.101.6.255:15000: connect: connection refused
```

And now the security group works as expected! 

**Attach logs**

**What you expected to happen**: I expected that the Security Group is correctly attached on the Pod with the very first deployment.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Helm installs the resource in a specific order but the CRD are always installed before the deployment: https://github.com/helm/helm/blob/release-3.0/pkg/releaseutil/kind_sorter.go#L27-L61

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:13:28Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.6-eks-49a6c0", GitCommit:"49a6c0bf091506e7bafcdb1b142351b69363355a", GitTreeState:"clean", BuildDate:"2020-12-23T22:10:21Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- 
- CNI Version: v1.7.9
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`): `Linux ip-10-101-11-22.eu-west-1.compute.internal 5.4.91-41.139.amzn2.x86_64 #1 SMP Tue Jan 19 20:10:53 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by Skaronator** [comment]
I'll see if I can get logs and a minimal helm chart to reproduce this unless I missed something really obviously.

**Comment by jayanthvn** [comment]
Hi @Skaronator 

On a first look this seems to be expected with any controllers since the controller (here vpc resource controller) might not be completely up and hence it fails for the first time. We will see if we can find a solution or workaround for this.

Thank you.

**Comment by abhipth** [comment]
Hi @Skaronator 

Thanks for reaching out. Just to give a bit of background - If the deployment/pod is created before the Security Group Policy then the webhook would not inject the resource limit to the pod.
```
Limits:
  vpc.amazonaws.com/pod-eni:  1
```

In the first pod that you shared the health check probe fails and then kubelet retries to create the container and this request would not go through the webhook as the webhook can only intercept the Pod create events to inject the resource limit. 

However, on deleting and Re-Creating the Pod the request would go through the webhook and if there is a matching SGP then the Pod should get the limit and request `vpc.amazonaws.com/pod-eni:` injected in the container.

I suspect that the SGP could have been created either after the deployment or in parallel with the deployment which could also lead to the issue. Could you share the order of events in which you deploy your manifests for instance - SGP is deployed first and Deployment second.

**Comment by Skaronator** [comment]
Hi @abhipth, thanks for reaching back.

We're using a single helm chart to deploy the SecurityGroupPolicy, Service, ServiceAccount, Deployment (and more) resources. Since we're using Helm we don't have any control over the order but looking into the source code I can see that Helm already takes care of it and installs CustomResourceDefinition way before the Deployment:

https://github.com/helm/helm/blob/041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622/pkg/releaseutil/kind_sorter.go#L31-L66

(CustomResourceDefinition = 13 / Deployment = 27)

Helm also wait for the resources to reach a ready state but I'm not sure if this is true for CRD.

**Comment by abhipth** [comment]
Hi @Skaronator 

I believe CustomResourceDefination and Custom Resources are different Kinds. For instance

`kubectl get crd` would return you follwoing CRDs which are of Kind `CustomResourceDefinition`
```
NAME                                         CREATED AT
eniconfigs.crd.k8s.amazonaws.com             2021-03-05T02:23:46Z
securitygrouppolicies.vpcresources.k8s.aws   2021-03-08T23:58:40Z
``` 
 
Whereas the SGP that you create is of kind `SecurityGroupPolicy` which is different from Kind `CustomResourceDefinition`.

As per this [GitHub Issue ](https://github.com/helm/helm/issues/4578) unknown Kinds are installed at the end which could explain the issue you are seeing.

I see one more open issue with helm on ordering of custom resources  - https://github.com/helm/helm/issues/8439

**Comment by Skaronator** [comment]
Hi @abhipth

You're completly right. After further investigation we found out that unknown kinds are installed at the end - e.g. after the Pod Deployment. So there is nothing the aws-cni can fix in this case. I'm going to close this and thank you for hinting me in the right direction.

**Comment by jarl-tornroos** [comment]
I had the same problem when using Helm, the SecurityGroupPolicy is the last to be installed. You can see it by adding the flag `--dry-run` to the Helm command.
I got the problem fixed by adding the annotation below to the SecurityGroupPolicy template.
```
annotations:
  "helm.sh/hook": "pre-install"
```

**Comment by JRemitz** [comment]
For posterity, anyone else ending up here it may be important to catch all "pre-" hooks:
```yaml
metadata:
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade,pre-rollback"
```
[Helm Hooks](https://helm.sh/docs/topics/charts_hooks/#the-available-hooks)
