### ISSUE TITLE
Can't access daemon set pods via status.hostIP & hostPort

### ISSUE THREAD

**Issue by sanjitsaluja** [aws/amazon-vpc-cni-k8s#141]
**Problem** I'm unable to access the `status.hostIP` from inside the pod container. This works just fine in GKE.

**Setup**
We are running FluentD daemon set. 

```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logger-fluentd
  labels:
    name: logger
spec:
  template:
    metadata:
      labels:
        name: logger
    spec:
      containers:
        - image: <my_fluentd_image>
          name: logger-fluentd
          ports:
            - containerPort: 24224
              hostPort: 24224
              protocol: TCP
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
      imagePullSecrets:
        - name: docker-login
      terminationGracePeriodSeconds: 30
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
  updateStrategy:
    type: RollingUpdate
```

Then the idea is to access these in individual pods. Here's how we inject the `status.hostIP` to our deployments.

```
   - name: LOGGER_SERVICE_HOST
    valueFrom:
        fieldRef:
          fieldPath: status.hostIP
```

**Problem**

```
telnet 192.168.39.18 24224
root@pod# telnet 192.168.39.18 24224
Trying 192.168.39.18...
telnet: Unable to connect to remote host: Connection refused
```
