### ISSUE TITLE
aws-node liveness probe failing when a custom ValidatingAdmissionWebhook is enabled in EKS 

### ISSUE THREAD

**Issue by bboppana** [aws/amazon-vpc-cni-k8s#1444]
**What happened**:

Enabled custom ValidatingAdmissionWebhook in an EKS cluster that checks for new or updated pods for specific labels to allow the deployment to procced. 

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: "${name}"
webhooks:
- name: "${name}"
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["pods"]
  clientConfig:
    service:
      name: "${servicename}"
      path: "${path}"
      namespace: "${namespace}"
    caBundle: ${cabundle}
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
```

After that, aws-node on every new worker node failing to start with below error and those nodes are not joining the cluster because no ENI or IPs are attached to it.

{"log":"ERROR: logging before flag.Parse: E0426 23:01:04.273184      10 memcache.go:138] couldn't get current server API group list; will keep using cached value. (Get https://10.100.0.1:443/api?timeout=32s: dial tcp 10.100.0.1:443: i/o timeout)\n","stream":"stderr","time":"2021-04-26T23:01:04.273387983Z"}

If i delete the custom ValidatingAdmissionWebhook, aws-node starts fine with no errors and node is then attached to the cluster.

**Question**

Is there specific configuration or RBAC needs to be added to use custom ValidatingAdmissionWebhook in EKS?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18
- CNI Version: 1.7.5
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2
- Kernel (e.g. `uname -a`): 4.14.209-160.339.amzn2.x86_64
