### ISSUE TITLE
Use of Service externalIPs with CNI custom networking

### ISSUE THREAD

**Issue by marco-a-itl** [aws/amazon-vpc-cni-k8s#1466]
**What happened**:
I followed AWS guide https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html to have pods use different subnets respect to nodes primary (original) subnets.
Then I assigned to a node primary ENI (which belongs to the original subnet, not to the new subnet dedicated to pods) a secondary IP address (`172.22.10.23`) to be used as `externalIP` in k8s Service description:
```
kind: Service
apiVersion: v1
metadata:
  name: udp-echo-server
  namespace: test
  labels:
    app: udp-echo-server
spec:
  selector:
    name: udp-echo-server
  ports:
  - name: udp
    protocol: UDP
    port: 33333
    targetPort: 33333
  externalIPs:
    - 172.22.10.23
```
The intent was to use the externalIP as a floating/virtual IP address (to be moved to another node in case of node failure).
However when a group of pods is started, one of them gets assigned with the same address as the externalIP, leading to address duplication (`172.22.10.23` is assigned to Service as `EXTERNAL-IP`, and to one of the pods as `IP`):
```
NAME                               READY   STATUS    RESTARTS   AGE   IP             NODE                                          NOMINATED NODE   READINESS GATES
udp-echo-server-8495b56dd9-kj9hs   1/1     Running   0          6s    172.16.0.29    ip-172-22-10-74.eu-south-1.compute.internal   <none>           <none>
udp-echo-server-8495b56dd9-mhc5v   1/1     Running   0          6s    172.16.0.22    ip-172-22-10-74.eu-south-1.compute.internal   <none>           <none>
udp-echo-server-8495b56dd9-z4ph2   1/1     Running   0          6s    172.22.10.23   ip-172-22-10-25.eu-south-1.compute.internal   <none>           <none>

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP    PORT(S)     AGE   SELECTOR
service/udp-echo-server   ClusterIP   10.100.69.21   172.22.10.23   33333/UDP   6s    name=udp-echo-server

``` 
If I start the same group of pods without assigning an externalIP to the Service, all the pods have addresses in the new subnets (`172.16.X.X`), which were intended to be used specifically for pods.
So it seems that, even with CNI custom network, the pods get IP addresses from a pool that includes _all_ the secondary IP addresses, no matter which ENI these addresses are associated to.

**What you expected to happen**:
With CNI custom networking I expected to have new subnets dedicated exclusively to pods.

**How to reproduce it (as minimally and precisely as possible)**:
* add new CIDR to VPC
* create two subnets (one for each AZ) from the new CIDR
* `kubectl set env daemonset aws-node -n kube-system AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG=true`
* `kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2` returns `v1.7.5`
* create and apply ENIConfig custom resources:
```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eu-south-1a
spec:
  securityGroups:
    - sg-0db2cef8d011e629f
  subnet: subnet-0e8cd07bbe4a6926f
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eu-south-1b
spec:
  securityGroups:
    - sg-0db2cef8d011e629f
  subnet: subnet-09f399cff4baee635
```
* `kubectl annotate node ip-172-22-10-31.eu-south-1.compute.internal k8s.amazonaws.com/eniConfig=eu-south-1a`
* `kubectl annotate node ip-172-22-10-69.eu-south-1.compute.internal k8s.amazonaws.com/eniConfig=eu-south-1b`
* `kubectl set env daemonset aws-node -n kube-system ENI_CONFIG_LABEL_DEF=failure-domain.beta.kubernetes.io/zone`
* terminate the nodes so that the autoscaling group creates two new nodes with the new ENIs attached
* `aws ec2 assign-private-ip-addresses --network-interface-id eni-03abbf92f22b78fc2 --private-ip-addresses 172.22.10.23`
* create a Deployment with three pods and a Service with `172.22.10.23` as externalIP
* one of the pods has IP `172.22.10.23`
