### ISSUE TITLE
EC2-Classic Instances intermittently cannot reach PODs via ClassicLink 

### ISSUE THREAD

**Issue by apryiomka** [aws/amazon-vpc-cni-k8s#1519]
**What happened**:
We are running EKS v1.17 with `amazon-k8s-cni:v1.7.5-eksbuild.1`

We currently in the middle of migration of our EC2 Classic services to EKS and as the result, we have enabled ClassicLink on our VPC and allows some services in EC2 Classic to talk to EKS via private IPs.

The problem we are seeing is that some pods are accessible in EKS via POD's IP / Secondary EC2 Worker Node's IPs, but some are not. The behaviour is somewhat sporadic as it is not specific to any service or a node. Same deployments have some PODs accessible, some not, same goes for the Nodes. On the same Node we have some PODs that can be accessed and some that can't.

One thing to notice is that the worker nodes are created with multiple ENI attachments with with different Primary / Secondary IP addresses. For instance, we have an EKS worker instance `ip-10-0-50-225.ec2.internal` with primary IP `10.0.50.225` and secondary IPs under the ENI attachment would be accessible via ClassicLink: 

```
NetworkInterfaces:
   - Attachment:
        DeleteOnTermination: true
        DeviceIndex: 0
        NetworkCardIndex: 0
        Status: attached
      PrivateDnsName: ip-10-0-50-225.ec2.internal
      PrivateIpAddress: 10.0.50.225
      Description: ''
      PrivateIpAddresses:
      - Primary: true
        PrivateDnsName: ip-10-0-50-225.ec2.internal
        PrivateIpAddress: 10.0.50.225
      - Primary: false
        PrivateDnsName: ip-10-0-53-0.ec2.internal
        PrivateIpAddress: 10.0.53.0
      - Primary: false
        PrivateDnsName: ip-10-0-55-66.ec2.internal
        PrivateIpAddress: 10.0.55.66
      - Primary: false
        PrivateDnsName: ip-10-0-45-197.ec2.internal
        PrivateIpAddress: 10.0.45.197
```
but none of these would be accessible via ClassicLink:

```
   - Attachment:
        DeleteOnTermination: true
        DeviceIndex: 3
        NetworkCardIndex: 0
        Status: attached
      Description: aws-K8S-i-********
      PrivateDnsName: ip-10-0-52-191.ec2.internal
      PrivateIpAddress: 10.0.52.191 <--- no ClassicLink accessible
      PrivateIpAddresses:
      - Primary: true
        PrivateDnsName: ip-10-0-52-191.ec2.internal
        PrivateIpAddress: 10.0.52.191 <--- no ClassicLink accessible
      - Primary: false
        PrivateDnsName: ip-10-0-52-193.ec2.internal
        PrivateIpAddress: 10.0.52.193 <--- no ClassicLink accessible
      - Primary: false
        PrivateDnsName: ip-10-0-61-69.ec2.internal
        PrivateIpAddress: 10.0.61.69 <--- no ClassicLink accessible
```

Any pods that happen to ends up with the IPs from the secondary / tertiary  (`DeviceIndex: > 0`) ENI doesn't seem to be able to get any ClassicLink traffic. Also we noticed that the _Primary_ ENI is crated without description or requestor ID, which seems like a "default" EC2 instance ENI. The second and third ENI are created with both requestor id: AROASG6EFR5*******:i-0b3e***** and description: aws-K8S-i-0b3e*** which implies that those are not created the same?
