### ISSUE TITLE
Calico networkpolicy enforcement does not allow Terminating pods to gracefully shut down when using non calico cni

### ISSUE THREAD

**Issue by primeroz** [aws/amazon-vpc-cni-k8s#1531]
**What happened**:
There is a known bug in calico used in the tigera-operator manifest for 1.7 and 1.8 - see https://github.com/projectcalico/calico/issues/4518

The bug causes the firewall to be removed as soon as a pod enter the termination state breaking the networking for the pod and preventing it from being able to do a graceful shutdown 

The bug is not present in version 3.15.5 of calico - Tigera Operator version 1.7.7 and at the moment downgrading to that is what is recommended on the calico slack. The current version of the tiger-operator in this repo for vpc 1.7 and 1.8 is broken though. 

There is a Fix in Master calico not released yet, apparently it will be backported all the way to 3.16 and hopefully a point release of the operator will be done. 

The manifests in this repo should be updated at least to that minor version of tigera-operator v1.13.X when that is released

**Attach logs**
See upstream bug https://github.com/projectcalico/calico/issues/4518

**What you expected to happen**:
See upstream bug https://github.com/projectcalico/calico/issues/4518

**How to reproduce it (as minimally and precisely as possible)**:
See upstream bug https://github.com/projectcalico/calico/issues/4518

**Anything else we need to know?**:
Right now to downgrade to the last known working version use the manifest from https://docs.projectcalico.org/archive/v3.15/manifests/tigera-operator.yaml and install the Installation as

```
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  # Configures Calico policy configured to work with AmazonVPC CNI networking.
  # cni:
  #   type: AmazonVPC
  kubernetesProvider: EKS
```

**Environment**:
- Kubernetes version (use `kubectl version`): EKS-1.19
- CNI Version: 1.7.10
- Calico Version : v1.13.2 / 3.17.1
