### ISSUE TITLE
initcontainer should have requests/limits

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1554]
**What would you like to be added**:
https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/master/aws-k8s-cni.yaml#L199
needs requests/limits

this has worked well for us:
```yaml
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            cpu: 200m
            memory: 128Mi
```

**Why is this needed**:
unlimited containers are can cause issues / are blocked by our cluster policies
