### ISSUE TITLE
Set preStop hook to prevent failures during node shutdown

### ISSUE THREAD

**Issue by grosser** [aws/amazon-vpc-cni-k8s#1556]
example errors:
```
Failed killing the pod "foo": failed to "KillPodSandbox" for "bar" with KillPodSandboxError: "rpc error: code = Unknown desc = networkPlugin cni failed to teardown pod \"foo\" network: del cmd: error received from DelNetwork gRPC call: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:50051: connect: connection refused\""
```

happen because cni shuts down quickly while other pods are still doing things on the node that is shutting down

we set
```
terminationGracePeriodSeconds: 190
```
and 
```
        lifecycle:
          preStop:
            exec:
              command:
              - "/bin/sh"
              - "-c"
              - echo 'preStop called, exiting in 180 seconds...'; sleep 180
```
to fix these, but ideally that would be upstream (or at lest documented somewhere) or we'd find some other solution for this
