### ISSUE TITLE
Inadvertent newline in eniconfig.crd.k8s.amazonaws.com resource spec results in misleading error 

### ISSUE THREAD

**Issue by nbrational** [aws/amazon-vpc-cni-k8s#1626]
**What would you like to be added**:
Better error handling for input data errors in ENIConfig CRD

**Why is this needed**:

When using custom CNI, an accidental null string in securityGroups list results in a failed CreateNetworkInterface with a vague error `Client.InvalidParameterValue: user <AWS_ACCOUNT_ID> does not own a resource`.

Steps to replicate:-
- follow steps on [this](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) link
- Use following for ENIConfig (note the null string in securityGroups list)
```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata: 
  name: ap-southeast-2a
spec: 
  securityGroups: 
    - sg-0c4e4101aaa30c2ff
    - ""
  subnet: subnet-039aec6e2329771e8
```
- IPAMD logs show following error

```
{"level":"error","ts":"2021-03-15T09:58:21.256Z","caller":"ipamd/ipamd.go:627","msg":"Failed to increase pool size due to not able to allocate ENI AllocENI: failed to create ENI: failed to create network interface: InvalidParameterValue: user &lt;ACCOUNT_ID&gt; does not own a resource\n\tstatus code: 400, request id: 345bb7c3-14a3-4f7b-a515-b2b3fc58daf7"}
```

- CloudTrail has a failed CreateNetworkInterface:-
```
"errorCode": "Client.InvalidParameterValue",
    "errorMessage": "user 307862320347 does not own a resource",
```

- Errors are vague and it wasn't easy to identify the input error
