### ISSUE TITLE
Pods attached to a Security Group is not able to communicate with cluster resources

### ISSUE THREAD

**Issue by yngvark** [aws/amazon-vpc-cni-k8s#1695]
**What happened**

It appears pods in a Security Group isn't able to connect with anything in my EKS cluster.

In my EKS-managed cluster (1.19), made with eksctl, if I put a pod in a security group, the pod is not able to communicate with anything inside the cluster, nor google.com (as it cannot reach any DNS servers I assume). However, pinging the IP of google.com from the pod works, and other pods can do requests with the pod attached to the security group.

What I expect is to be able to reach services in my cluster, especially CoreDNS, so that pods in security groups can talk to other pods by their service name. What am I missing?

Details:

See the bottom of this issue for the Kubernetes manifests I'm using.

In the following command, `debugger` is the pod attached to a security group that allows all inbound and outbound traffic (0.0.0.0/0 and ::/0). 

Some attempts to reach stuff in cluster or Internet:

```shell
$ kubectl exec -it debugger -- bash

# Pod's terminal
$ curl -I google.com
curl: (6) Could not resolve host: google.com

$ nslookup google.com
;; connection timed out; no servers could be reached

$ curl nginx-svc # nginx running in the same namespace
curl: (6) Could not resolve host: nginx-svc

$ ping 142.250.74.46 # IP of google.com
PING 142.250.74.14 (142.250.74.14): 56 data bytes
64 bytes from 142.250.74.14: seq=0 ttl=45 time=41.638 ms
```

So nothing except pinging the IP of google.com works.

Kubernetes events looks fine:

```shell
2s          Normal    Scheduled                pod/debugger      Successfully assigned test/debugger to ip-192-168-7-235.eu-west-1.compute.internal
2s          Normal    SecurityGroupRequested   pod/debugger      Pod will get the following Security Groups [sg-xxxxxxxxxxxxxxxx]
1s          Warning   FailedCreatePodSandBox   pod/debugger      Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "b540ec29d71f866822bc80becd55a22c48518e9984893a697bbe955232d82e3e" network for pod "debugger": networkPlugin cni failed to set up pod "debugger_test" network: add cmd: failed to assign an IP address to container
1s          Normal    SandboxChanged           pod/debugger      Pod sandbox changed, it will be killed and re-created.
1s          Normal    ResourceAllocated        pod/debugger      Allocated [{"eniId":"eni-0124ff6976f71d35c","ifAddress":"0a:cf:44:79:34:47","privateIp":"192.168.7.171","vlanId":1,"subnetCidr":"192.168.7.0/24"}] to the pod


```

From a pod with no security group, this works fine:

```shell
$ kubectl run test --image=nginx --command -- curl -I google.com
...
HTTP/1.1 301 Moved Permanently
...

$ kubectl run test --image=nginx --command -- curl -I nginx-svc
...
HTTP/1.1 200 OK
...
```

`resolv.conf` looks fine:

```shell
$ kubectl exec -it debugger -- cat /etc/resolv.conf
nameserver 10.100.0.10
search test.svc.cluster.local svc.cluster.local cluster.local eu-west-1.compute.internal
options ndots:5
```

Finally, a pod with _no_ security group attached is able to do requests to the pod _with_ the security group,
so apparently incoming requests to a pod with securitygroup is fine:

```shell
$ kubectl run test --image=nginx --command -- curl -I debugger
...
HTTP/1.1 200 OK
...
```

**Other info**

* I believe all points in "Consideration" in https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html is covered

* I have set DISABLE_TCP_EARLY_DEMUX=true so probes work, as described [here](https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html)

**Environment**:
- Kubernetes version (use `kubectl version`): 1.19.
- CNI Version: I tried v1.7.5-eksbuild.2, v1.8.0-eksbuild.1 and v1.9.0-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Not sure, it's managed by eksctl. AMI name: amazon-eks-node-1.19-v20210826
- Kernel (e.g. `uname -a`): Not sure, it's managed by eksctl. AMI name: amazon-eks-node-1.19-v20210826
- eksctl version: 0.0.49 and 0.0.70 (I tried both)

The Kubernetes manifests I'm using:

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  containers:
  - name: debugger
    image: yngvark/linuxtools-nginx # nginx plus more cli tools
  terminationGracePeriodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: debugger
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: debugger
  type: NodePort

---

apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: debugger
spec:
  podSelector:
    matchLabels:
      app: debugger
  securityGroups:
    groupIds:
    - sg-xxxxxxxxxxxxxxxx

```

**Comment by yngvark** [comment]
That issue looks similar, but I'm not using node local DNS.

However, I contacted AWS support, which were able to resolve my case.

It seems my security groups were wrongly configured. Even if my security group was allowing all traffic out, the security groups for the k8s control plane and my self managed node group didn't allow traffic in from the pod security group. I'm running Fargate for my kube-system namespace, so the following point from the documentation is then relevant:

> If you're using the security group policy with Fargate, make sure that your security group has rules that allow the pods to communicate with the Kubernetes control plane. The easiest way to do this is to specify the cluster security group as one of the security groups.

Source: https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html#security-groups-pods-deployment

There is two solutions to this issue:
* Add inbound rule to security groups for control plane and node group
* Add the control plane security group to my SecurityGroupPolicy k8s manifest

I did the last, so my security group now looks something like this:

```
apiVersion: vpcresources.k8s.aws/v1beta1
kind: SecurityGroupPolicy
metadata:
  name: debugger
  namespace: test
spec:
  podSelector:
    matchLabels:
      app: debugger
  securityGroups:
    groupIds:
    - sg-xxxxxxxxxxxxxxxxxx # debug pod
    - sg-yyyyyyyyyyyyyyyyyy # control plane
```

For reference, eksctl puts the following description on the security groups I'm talking about:
* control plane security group: "EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads."
*  cluster shared node security group: "Communication between all nodes in the cluster"
