### ISSUE TITLE
Hardcoded settings in custom-resources.yaml for aws-calico

### ISSUE THREAD

**Issue by nserev** [aws/amazon-vpc-cni-k8s#1758]
Following the examples and documentation I expected that if I put settings in the installation section of the values.yaml file for aws-calico, those settings will be applied. For example in the default values.yaml we have:

```
kubernetesProvider: "EKS"
```
I wanted to update the registry, so I can avoid the limitations of docker.io, but those settings have never been able to apply. After a bit of research I've found that the original version of custom-resources.yaml allows updating the installationspec, but not the one here.

Original file is:

```
{{ if .Values.installation.enabled }}
{{ $installSpec := omit .Values.installation "enabled" }}
{{ $secrets := list }}
{{ range $name := keys .Values.imagePullSecrets -}}
{{ $item := dict "name" $name }}
{{ $secrets = append $secrets $item }}
{{ end }}
{{ $_ := set $installSpec "imagePullSecrets" $secrets }}

apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
{{ $installSpec | toYaml | indent 2 }}

{{ end }}
```
Current version here is:

```
# This section includes base Calico installation configuration.
# For more information, see: https://docs.projectcalico.org/v3.17/reference/installation/api#operator.tigera.io/v1.Installation
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
  annotations:
    "helm.sh/hook": post-install
spec:
  # Configures Calico policy configured to work with AmazonVPC CNI networking.
  cni:
    type: AmazonVPC
```

Please sync with the upstream version of the helm chart and allow custom configuration via values.yaml file. I am expecting custom settings like this one

```
installation:
  enabled: true
  kubernetesProvider: "EKS"
  registry: "docker.mycompany.io"
```

to work. For more information you can check the installation spec document here

https://docs.projectcalico.org/reference/installation/api#operator.tigera.io/v1.InstallationSpec
