### ISSUE TITLE
PostStart lifecycle hook running before pod networking is fully ready

### ISSUE THREAD

**Issue by sean-redmond** [aws/amazon-vpc-cni-k8s#1790]
My pod needs network connectivity to start and I am using a postStart lifecycle hook that waits until it is ready and then does something that needs network connectivity. However it seems networking fails to be operational when using this postStart lifecycle hook, the below is a simple test case to see the issue:

```
apiVersion: v1
kind: Pod
metadata:
  name: debug
spec:
  containers:
  - name: ubuntu
    image: tutum/dnsutils
    command:
      - "sleep"
      - "604800"
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - ping -c1 8.8.8.8 >> /proc/1/fd/1; ping -c1 8.8.8.8 >> /proc/1/fd/1
```

I send stdout to the stdout of pid1 just so its easy to grab the logs:

```
$ kubectl logs debug -p
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
```

From the above you can see we are unable to get a response to a ping test when inside the postStart lifecycle, 

EKS version = 1.21
HostOS = bottlerocket-aws-k8s-1.21-x86_64-v1.2.0-ccf1b754, AMI = ami-07d5246d9a028407d
CNI = v1.9.0-eksbuild.1

My assumption here is the lifecycle hook is running before some CNI phase is completed.

**Comment by Shreya027** [comment]
Hi, 
From my research on hook execution, I read that for a PostStart hook, the Container ENTRYPOINT and hook fire asynchronously. We have an entrypoint.sh script (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/scripts/entrypoint.sh) in the VPC CNI repo. The script exists so that  we start the IPAM daemon and wait until we know it  running successfully before copying the CNI plugin binary and its configuration file to the well-known directory that kubelet looks in. So, there could possibly be a race condition in which the hook is executed before the  necessary initial  CNI setup is in place.

Also to debug any error in PostStart hook, it would be good to check for event broadcasts made by the hook. For PostStart apparently there  is the FailedPostStartHook event. Try checking if any error event is present by running  ```kubectl describe pod <pod_name>```

**Comment by achevuru** [comment]
Hook should execute post the container is created and that should happen post the Pod's networking is setup. kubelet will not proceed with further setup until CNI was able to successfully setup Pod networking. CNI doesn't control the order of container lifecycle hook executions...

Have you checked if you are able to reach `8.8.8.8` from within the pod? You can remove the `PostStart` hook and let the pod come up, then `exec` in to the pod and try pinging the same IP. Might be a generic connectivity issue.

**Comment by sean-redmond** [comment]
If I remove the PostStart hook and exec into the pod networking works as expected. 

It seems the networking is just not fully up when running scripts in PostStrat phase including simple things like ping 8.8.8.8. 

I moved my script from PostStart into enterypoint.sh and it works fine.

**Comment by Shreya027** [comment]
Thanks for the update @sean-redmond ! Since it works fine for you now, I'll close the issue.

**Comment by sean-redmond** [comment]
I think this is still an issue, what I have is really a work around by not using the PostStart life-cycle hook, and just moving the script to run in entry point - This issue still warrants further investigation as someone may have a stronger use case meaning they need this hook and the workaround is not an option for them.

**Comment by lapwat** [comment]
I do have the same issue.

I want to wait for my `redis` container to be ready to accept connexions before my Pod switches Ready state.

```yaml
lifecycle:
  postStart:
    exec:
      command: ["/bin/sh", "-c", "while ! redis-cli ping; do echo hello; sleep 2; done"]
```

The problem here is that the `redis` container is not reachable during the `postStart` phase. Which means that my pod will never enter the `Running` state.

If I remove the `postStart` command and simply run `while ! redis-cli ping; do echo hello; sleep 2; done` after the container is in the `Ready` state, I can reach the redis server Pod.

If it is not the way to do a "wait before my container is ready" phase, I would be happy to do it another way.
