### ISSUE TITLE
Small typo in the latest aws-k8s-cni.yaml

### ISSUE THREAD

**Issue by cablespaghetti** [aws/amazon-vpc-cni-k8s#183]
I just noticed this typo in the YAML. Although it doesn't seem to stop things working in my cluster.

https://github.com/aws/amazon-vpc-cni-k8s/blob/8d6101d72fe34159487688e662c0a91cdc6f08cf/config/v1.2/aws-k8s-cni.yaml#L12

**Comment by xdrus** [comment]
Also, there are two other issues:
1) typo in CustomResource definition [should be 'singular'](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.2/aws-k8s-cni.yaml#L127).
2) There is no field ['spec.names.scope'](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.2/aws-k8s-cni.yaml#L125) (at least at [1.11 docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.11/#customresourcedefinitionnames-v1beta1-apiextensions-k8s-io))

```
error: error validating "/tmp/cluster/components/20_aws-k8s-cni.yaml": error validating data: [ValidationError(CustomResourceDefinition.spec.names): unknown field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionNames, ValidationError(CustomResourceDefinition.spec.names): unknown field "singuar" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionNames]; if you choose to ignore these errors, turn validation off with --validate=false
```

fixed variant (works for our 1.11.3 cluster):
```yaml
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
spec:
  scope: Cluster
  group: crd.k8s.amazonaws.com
  version: v1alpha1
  names:
    plural: eniconfigs
    singular: eniconfig
    kind: ENIConfig
```
