### ISSUE TITLE
Helm chart compatibility with EKS docs

### ISSUE THREAD

**Issue by louismrose** [aws/amazon-vpc-cni-k8s#1917]
**What happened**:

I've been following the [CNI custom networking instructions](https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html) in the EKS docs.

Step 5c recommends setting the following env var on the VPC CNI daemonset:
> ENI_CONFIG_LABEL_DEF=topology.kubernetes.io/zone

Step 5a recommends creating ENIConfigs manually via `kubectl`.

I was hoping to use the Helm chart in this repo to install the ENIConfigs, and otherwise manage upgrades to the VPC CNI add on. However, by default the Helm chart names ENIConfig using the format `REGION` + `USER-SUPPLIED-NAME`. But EKS doesn't put any label on nodes by default that matches this format.

Is this intentional? It feels a little like the Helm chart should produce names that work well with `ENI_CONFIG_LABEL_DEF` (etc) out-of-the-box?

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21
- CNI Version: v1.9.0 (Helm chart 1.1.8)
- OS (e.g: `cat /etc/os-release`): not relevant
- Kernel (e.g. `uname -a`): not relevant

**Comment by jayanthvn** [comment]
Thanks, we just need `$key` here - https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/eniconfig.yaml#L6. I did a quick test upon removing and eniconfig is generated fine - 

```
---
# Source: aws-vpc-cni/templates/eniconfig.yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: us-west-2a
spec:
  securityGroups:
    - sg-123
  subnet: subnet-123
---
# Source: aws-vpc-cni/templates/eniconfig.yaml
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: us-west-2b
spec:
  securityGroups:
    - sg-456
  subnet: subnet-456
---
I will open a PR and fix this up.
```
