### ISSUE TITLE
Error with version 1.2 yaml

### ISSUE THREAD

**Issue by rickardrosen** [aws/amazon-vpc-cni-k8s#198]
The yaml does not go through k8s validation:

```
error: error validating "https://raw.githubusercontent.com/aws/amazon-vpc-cni-k8s/master/config/v1.2/aws-k8s-cni.yaml": error validating data: ValidationError(CustomResourceDefinition.spec.names): unknown field "scope" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.CustomResourceDefinitionNames; if you choose to ignore these errors, turn validation off with --validate=false
```
 
Scope seems to have snuck in here:
```
spec:
  scope: Cluster
  group: crd.k8s.amazonaws.com
  version: v1alpha1
  names:
    **scope: Cluster**
```

Looking through the API spec "scope" is not valid for "Names so the validation error makes sense.
