### ISSUE TITLE
ENIConfig resource name change breaks deployment (Helm 1.1.12 to 1.1.16)

### ISSUE THREAD

**Issue by jacobbraaten** [aws/amazon-vpc-cni-k8s#1981]
**What happened**:
After upgrading the our Helm chart from 1.1.12 to 1.1.16 (app version 1.10.1 to 1.11.0) we noticed that our pods were getting stuck in `ContainerCreating`. We tracked it done to the CNI thinking that there was no available IPs for it to assign pods to. This was incorrect as the subnets in AWS had plenty of available IPs. 

After more digging it was noticed that the `ENIConfig` names did match what we expected them to be. In other clusters that have this running and that have not gone through the upgrade the names of the `ENIConfig's` were `<aws-region><letter>` however on the upgraded cluster they were just `<letter>`

After that I found this commit https://github.com/aws/amazon-vpc-cni-k8s/commit/f84db36eae600c28d8c736710fc379047881767c which changed how the ENIConfigs were named. 

To test the theory that the ENIConfig names were expected to be `<aws-region><letter>` i manually recreated them. After they were renamed our pods started to schedule again.

On to the question. Why was this name changed? Do we have a bad config and need to change it? Any help is appreciated in resolving this issue.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.22
- CNI Version: 1.11.0
- Helm Chart Version: 1.1.16

**Comment by jacobbraaten** [comment]
We have tracked down the issue. We had set the following environment variable `ENI_CONFIG_LABEL_DEF: topology.kubernetes.io/zone`. Which was done because of the suggestions in step 5 here https://docs.aws.amazon.com/eks/latest/userguide/cni-custom-network.html. 

However, with the change to the Helm chart this is no longer possible. Removal of the above config does solve the problem, but seems to break the guidance provided by AWS

**Comment by jacobbraaten** [comment]
We did still want to keep the above config, so we took the AWS Region in question and simply prepended it to the subnet key name in the configmap. Had concerns this might affect the code execution but it appears that is not the case.

Before:
```
    eniConfig:
      create: true
      region: us-east-1
      subnets:
        a:
          id: <id>
          securityGroups:
            - sg-1
```

After:
```
    eniConfig:
      create: true
      region: us-east-1
      subnets:
        us-east-1a:
          id: <id>
          securityGroups:
            - sg-1
```
