### ISSUE TITLE
Switching AWS_VPC_CNI_NODE_PORT_SUPPORT to false breaks SNAT for Pods

### ISSUE THREAD

**Issue by antoninbas** [aws/amazon-vpc-cni-k8s#2025]
**What happened**:
When setting `AWS_VPC_CNI_NODE_PORT_SUPPORT` to false for `aws-node`, SNAT breaks for all Pods for which the IP is assigned from a secondary network interface / ENI.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create a default EKS cluster with a single Node, and use a "small-ish" instance type (so that the primary ENI can support a smaller number of addresses). For example: `eksctl create cluster -N 1 --ssh-access --node-type t3.medium`.
2) Edit the `aws-node` Deployment to set `AWS_VPC_CNI_NODE_PORT_SUPPORT` to false. `AWS_VPC_K8S_CNI_EXTERNALSNAT` should remain set to false, so that the CNI is responsible for SNATting Pod traffic.
3) Create a Deployment with 5 replicas. There is a single Node so all 5 Pods will run on that Node. For example, `kubectl apply` the following YAML:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
spec:
  replicas: 5
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      containers:
      - name: toolbox
        image: antoninbas/toolbox
        command: ["sleep", "3600"]
```
4) check which Pods are assigned to a secondary ENI. I do this by running `ip rule list` and matching the rules for route table to to Pod IPs.
5) exec into one of these Pods and ping `8.8.8.8`. It will fail.

**Anything else we need to know?**:

This is caused by some incorrect iptables rules:
* https://github.com/aws/amazon-vpc-cni-k8s/blob/f979630f9d740bbc0ef26135b05ccffdd4ab841f/pkg/networkutils/network.go#L628-L637 is in the `nat` table and hence only applies to the first packet of the connection
* https://github.com/aws/amazon-vpc-cni-k8s/blob/f979630f9d740bbc0ef26135b05ccffdd4ab841f/pkg/networkutils/network.go#L529-L538 should be installed if `AWS_VPC_CNI_NODE_PORT_SUPPORT` is true OR if `AWS_VPC_K8S_CNI_EXTERNALSNAT` false (default).

Additionally, `mainENIRule` IP rule also needs to be installed, and loose rpf_filter needs to be configured.

I will submit a PR with these changes.

**Environment**:
eksctl version
```
0.105.0-rc.0
```
K8s version
```
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.10-eks-84b4fe6", GitCommit:"cc6a1b4915a99f49f5510ef0667f94b9ca832a8a", GitTreeState:"clean", BuildDate:"2022-06-09T18:24:04Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

credit also goes to my colleague @tnqn for investigating this
