### ISSUE TITLE
Pod's branch ENI intermittently not assigned security group from SecurityGroupPolicy

### ISSUE THREAD

**Issue by mikebreed** [aws/amazon-vpc-cni-k8s#2163]
A pod which definitely matched a SecurityGroupPolicy was instead assigned the node's security group on it's branch ENI. A different pod, based on the same Deployment & Replicaset, even assigned to the same node (and with the same aws-node pod on that node) had the security group correctly assigned to the branch ENI. I discovered this while trying to chase down why it seemed intermittent that sometimes the pod would be able to connect to the database and sometimes it couldn't. The intermittent behavior has been seen in two different clusters.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.21.14-eks-fb459a0
- CNI Version v1.11.0-eksbuild.1  (also see with v1.12.0-eksbuild.1)
- OS (e.g: `cat /etc/os-release`): amazon-eks-node-1.21-v20220914 / EKS Kubernetes Worker AMI with AmazonLinux2 image, (k8s: 1.21.14, docker: 20.10.17-1.amzn2, containerd: 1.6.6-1.amzn2) (ami-051aa0d5889741142 in us-east-2)
- Node: m5a.xlarge, amd64
- VPC CNI Image: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon-k8s-cni:v1.11.0-eksbuild.1
- VPC CNI settings:
```yaml
  - env:
    - name: ADDITIONAL_ENI_TAGS
      value: '{}'
    - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
      value: "true"
    - name: AWS_VPC_ENI_MTU
      value: "9001"
    - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
      value: "false"
    - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
      value: "false"
    - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
      value: "false"
    - name: AWS_VPC_K8S_CNI_LOGLEVEL
      value: DEBUG
    - name: AWS_VPC_K8S_CNI_LOG_FILE
      value: /host/var/log/aws-routed-eni/ipamd.log
    - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
      value: prng
    - name: AWS_VPC_K8S_CNI_VETHPREFIX
      value: eni
    - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
      value: /var/log/aws-routed-eni/plugin.log
    - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
      value: DEBUG
    - name: DISABLE_INTROSPECTION
      value: "false"
    - name: DISABLE_METRICS
      value: "false"
    - name: ENABLE_POD_ENI
      value: "true"
    - name: MY_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: WARM_ENI_TARGET
      value: "1"
    - name: ENABLE_IPv4
      value: "true"
    - name: ENABLE_IPv6
      value: "false"
```
### Pod where ENI used incorrect security group:
**ipamd.log**
```json
{"level":"info","ts":"2022-12-15T02:29:32.986Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /proc/28506/ns/net, Sandbox 44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936, ifname eth0"}
{"level":"debug","ts":"2022-12-15T02:29:32.986Z","caller":"rpc/rpc.pb.go:713","msg":"AddNetworkRequest: K8S_POD_NAME:\"tolgee-845cb5bb98-d6jbh\" K8S_POD_NAMESPACE:\"prod\" K8S_POD_INFRA_CONTAINER_ID:\"44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936\" ContainerID:\"44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936\" IfName:\"eth0\" NetworkName:\"aws-cni\" Netns:\"/proc/28506/ns/net\""}
{"level":"debug","ts":"2022-12-15T02:29:33.018Z","caller":"rpc/rpc.pb.go:713","msg":"Pod vlandId: 1"}
{"level":"debug","ts":"2022-12-15T02:29:33.019Z","caller":"rpc/rpc.pb.go:713","msg":"VPC CIDR 10.239.0.0/17"}
{"level":"info","ts":"2022-12-15T02:29:33.019Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr 10.239.39.1, IPv6Addr: , DeviceNumber: -1, err: <nil>"}
```
**plugin.log**
```json
{"level":"info","ts":"2022-12-15T02:29:32.984Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received CNI add request: ContainerID(44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936) Netns(/proc/28506/ns/net) IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod;K8S_POD_NAME=tolgee-845cb5bb98-d6jbh;K8S_POD_INFRA_CONTAINER_ID=44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"debug","ts":"2022-12-15T02:29:32.984Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Prev Result: <nil>\n"}
{"level":"debug","ts":"2022-12-15T02:29:32.984Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"MTU value set is 9001:"}
{"level":"info","ts":"2022-12-15T02:29:33.020Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received add network response from ipamd for container 44166400ff9f843da1271c733e864285662ce9c35aad4f08c80c9a8df8461936 interface eth0: Success:true IPv4Addr:\"10.239.39.1\" DeviceNumber:-1 VPCv4CIDRs:\"10.239.0.0/17\" PodVlanId:1 PodENIMAC:\"06:ee:bb:5f:4d:b2\" PodENISubnetGW:\"10.239.32.1\" ParentIfIndex:3"}
{"level":"debug","ts":"2022-12-15T02:29:33.020Z","caller":"routed-eni-cni-plugin/cni.go:220","msg":"SetupBranchENIPodNetwork: hostVethName=vlan763f3398675, contVethName=eth0, netnsPath=/proc/28506/ns/net, v4Addr=10.239.39.1/32, v6Addr=<nil>, vlanID=1, eniMAC=06:ee:bb:5f:4d:b2, subnetGW=10.239.32.1, parentIfIndex=3, mtu=9001, podSGEnforcingMode=strict"}
{"level":"debug","ts":"2022-12-15T02:29:33.050Z","caller":"driver/driver.go:324","msg":"Successfully disabled IPv6 RA and ICMP redirects on hostVeth vlan763f3398675"}
{"level":"debug","ts":"2022-12-15T02:29:33.077Z","caller":"driver/driver.go:356","msg":"Successfully setup container route, containerAddr=10.239.39.1/32, hostVeth=vlan763f3398675, rtTable=101"}
{"level":"debug","ts":"2022-12-15T02:29:33.077Z","caller":"driver/driver.go:356","msg":"Successfully setup fromHostVlan rule, hostVlan=vlan.eth.1, rtTable=101"}
{"level":"debug","ts":"2022-12-15T02:29:33.077Z","caller":"driver/driver.go:356","msg":"Successfully setup fromHostVeth rule, hostVeth=vlan763f3398675, rtTable=101"}
{"level":"debug","ts":"2022-12-15T02:29:33.077Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Using dummy vlanInterface: {Name:dummy763f3398675 Mac:1 Sandbox:}"}
```
![ENI](https://user-images.githubusercontent.com/36433470/207776236-5c4ad9cf-42a3-45f3-a46f-2add35d48f87.png)
### Po where ENI was assigned correctly (on same node even)
**ipamd.log**
```json
{"level":"info","ts":"2022-12-15T04:05:27.948Z","caller":"rpc/rpc.pb.go:713","msg":"Received AddNetwork for NS /proc/16376/ns/net, Sandbox 553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293, ifname eth0"}
{"level":"debug","ts":"2022-12-15T04:05:27.948Z","caller":"rpc/rpc.pb.go:713","msg":"AddNetworkRequest: K8S_POD_NAME:\"tolgee-845cb5bb98-7t29m\" K8S_POD_NAMESPACE:\"prod\" K8S_POD_INFRA_CONTAINER_ID:\"553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293\" ContainerID:\"553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293\" IfName:\"eth0\" NetworkName:\"aws-cni\" Netns:\"/proc/16376/ns/net\""}
{"level":"debug","ts":"2022-12-15T04:05:27.976Z","caller":"rpc/rpc.pb.go:713","msg":"Pod vlandId: 1"}
{"level":"debug","ts":"2022-12-15T04:05:27.977Z","caller":"rpc/rpc.pb.go:713","msg":"VPC CIDR 10.239.0.0/17"}
{"level":"info","ts":"2022-12-15T04:05:27.977Z","caller":"rpc/rpc.pb.go:713","msg":"Send AddNetworkReply: IPv4Addr 10.239.36.120, IPv6Addr: , DeviceNumber: -1, err: <nil>"}
```
**plugin.log**
```json
{"level":"info","ts":"2022-12-15T04:05:27.946Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received CNI add request: ContainerID(553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293) Netns(/proc/16376/ns/net) IfName(eth0) Args(IgnoreUnknown=1;K8S_POD_NAMESPACE=prod;K8S_POD_NAME=tolgee-845cb5bb98-7t29m;K8S_POD_INFRA_CONTAINER_ID=553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293) Path(/opt/cni/bin) argsStdinData({\"cniVersion\":\"0.4.0\",\"mtu\":\"9001\",\"name\":\"aws-cni\",\"pluginLogFile\":\"/var/log/aws-routed-eni/plugin.log\",\"pluginLogLevel\":\"DEBUG\",\"podSGEnforcingMode\":\"strict\",\"type\":\"aws-cni\",\"vethPrefix\":\"eni\"})"}
{"level":"debug","ts":"2022-12-15T04:05:27.947Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Prev Result: <nil>\n"}
{"level":"debug","ts":"2022-12-15T04:05:27.947Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"MTU value set is 9001:"}
{"level":"info","ts":"2022-12-15T04:05:27.978Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Received add network response from ipamd for container 553a8e02e6ebb9b8b6e8b70137585447fc62003c50e186596d4bc785bb253293 interface eth0: Success:true IPv4Addr:\"10.239.36.120\" DeviceNumber:-1 VPCv4CIDRs:\"10.239.0.0/17\" PodVlanId:1 PodENIMAC:\"06:06:fe:8d:30:ac\" PodENISubnetGW:\"10.239.32.1\" ParentIfIndex:3"}
{"level":"debug","ts":"2022-12-15T04:05:27.978Z","caller":"routed-eni-cni-plugin/cni.go:220","msg":"SetupBranchENIPodNetwork: hostVethName=vlana3ad740d262, contVethName=eth0, netnsPath=/proc/16376/ns/net, v4Addr=10.239.36.120/32, v6Addr=<nil>, vlanID=1, eniMAC=06:06:fe:8d:30:ac, subnetGW=10.239.32.1, parentIfIndex=3, mtu=9001, podSGEnforcingMode=strict"}
{"level":"debug","ts":"2022-12-15T04:05:28.001Z","caller":"driver/driver.go:324","msg":"Successfully disabled IPv6 RA and ICMP redirects on hostVeth vlana3ad740d262"}
{"level":"debug","ts":"2022-12-15T04:05:28.010Z","caller":"driver/driver.go:356","msg":"Successfully setup container route, containerAddr=10.239.36.120/32, hostVeth=vlana3ad740d262, rtTable=101"}
{"level":"debug","ts":"2022-12-15T04:05:28.011Z","caller":"driver/driver.go:356","msg":"Successfully setup fromHostVlan rule, hostVlan=vlan.eth.1, rtTable=101"}
{"level":"debug","ts":"2022-12-15T04:05:28.011Z","caller":"driver/driver.go:356","msg":"Successfully setup fromHostVeth rule, hostVeth=vlana3ad740d262, rtTable=101"}
{"level":"debug","ts":"2022-12-15T04:05:28.011Z","caller":"routed-eni-cni-plugin/cni.go:128","msg":"Using dummy vlanInterface: {Name:dummya3ad740d262 Mac:1 Sandbox:}"}
```
This screenshot shows a different pod / eni, but this was the same result I saw when it worked correctly
![ENI](https://user-images.githubusercontent.com/36433470/207776618-003ec6a8-e5d8-433f-bc0e-94cdb611c378.png)
