### ISSUE TITLE
Configuration via configure-addon doesn't take effect

### ISSUE THREAD

**Issue by mindw** [aws/amazon-vpc-cni-k8s#2272]
**What happened**:
AWS API and k8s seems to disagree on what the configuration of VPC-CNI should be:
```
$ aws eks describe-addon --addon-name vpc-cni  -cluster-name XXXX
{
    "addon": {
        "addonName": "vpc-cni",
        "clusterName": "XXXX",
        "status": "ACTIVE",
        "addonVersion": "v1.12.1-eksbuild.2",
        "health": {
            "issues": []
        },
        "addonArn": "arn:aws:eks:XXXXXX:XXXXXXX:addon/XXXXX/vpc-cni/a0c2f573-c76f-3cd8-2e8a-eafed09dcef2",
        "createdAt": "2023-01-25T21:48:43.040000+00:00",
        "modifiedAt": "2023-02-16T06:56:56.244000+00:00",
        "tags": {},
        "configurationValues": "{\"env\":{\"ANNOTATE_POD_IP\":\"true\",\"ENABLE_PREFIX_DELEGATION\":\"true\",\"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\",\"WARM_PREFIX_TARGET\":\"1\"}}"
    }
}
kubectl -n kube-system ds aws-node -o jsonpath='{.spec.template.spec.containers[*].env[?(@.name=="ENABLE_PREFIX_DELEGATION")]}{"\n"}'
{"name":"ENABLE_PREFIX_DELEGATION","value":"false"}
```

Applied configuration via Terraform
```
data "aws_eks_addon_version" "kube_proxy" {
  addon_name         = "kube-proxy"
  kubernetes_version = "1.23"
  most_recent        = true
}

data "aws_eks_addon_version" "vpc_cni" {
  addon_name         = "vpc-cni"
  kubernetes_version = "1.23"
  most_recent        = true
}

# Dirty tricks to avoid a race between addon and node creation. Mitigates:
# 1. Very long coredns addon creation (15min!)
# 2. vpc-cni not getting the correct configuration despite AWS API reporting otherwise
# https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1801#issuecomment-1211751717
resource "time_sleep" "wait_3_minutes" {
  depends_on = [
    null_resource.update_kubeconfig,
  ]

  create_duration = "3m"
}

resource "aws_eks_addon" "kube_proxy" {
  cluster_name      = module.eks.cluster_id
  addon_name        = "kube-proxy"
  resolve_conflicts = "OVERWRITE"
  addon_version     = data.aws_eks_addon_version.kube_proxy.version
  depends_on = [
    time_sleep.wait_3_minutes,
  ]
}

resource "aws_eks_addon" "vpc_cni" {
  cluster_name      = module.eks.cluster_id
  addon_name        = "vpc-cni"
  resolve_conflicts = "OVERWRITE"
  addon_version     = data.aws_eks_addon_version.vpc_cni.version
  # Reference docs https://docs.aws.amazon.com/eks/latest/userguide/cni-increase-ip-addresses.html
  # https://docs.aws.amazon.com/eks/latest/userguide/security-groups-for-pods.html
  # https://docs.aws.amazon.com/eks/latest/userguide/calico.html
  configuration_values = jsonencode({
    env = {
      ENABLE_PREFIX_DELEGATION          = "true"
      WARM_PREFIX_TARGET                = "1"
      ANNOTATE_POD_IP                   = "true"
      POD_SECURITY_GROUP_ENFORCING_MODE = "standard"
    }
  })

  depends_on = [
    aws_eks_addon.kube_proxy
  ]
}

```

**Attach logs**
There no relevant logs to attach.

**What you expected to happen**:
The configuration to take hold. This is especially painful as the nodes are started with 110 max-pods and pods are stuck at `ContainerCreation` state as the CNI attempts to add more ENIs.

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster using terraform with self managed nodes and the above addon TF configuration. execute
```
kubectl -n kube-system ds aws-node -o jsonpath='{.spec.template.spec.containers[*].env[?(@.name=="ENABLE_PREFIX_DELEGATION")]}{"\n"}'
```

**Anything else we need to know?**:
The behaviour isn't consistent - sometimes the configuration takes hold, sometimes it doesn't. I happens both on update and when creating new clusters. So far, re-applying the *SAME* configuration followed by starting ASG instance replacement resolves the issue.
```
aws eks update-addon --addon-name vpc-cni --cluster-name XXXX --resolve-conflicts OVERWRITE --configuration-values "{\"env\":{\"ANNOTATE_POD_IP\":\"true\",\"ENABLE_PREFIX_DELEGATION\":\"true\",\"POD_SECURITY_GROUP_ENFORCING_MODE\":\"standard\",\"WARM_PREFIX_TARGET\":\"1\"}}"
```

**Environment**:
- Kubernetes version
```
$ k version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.26.1
Kustomize Version: v4.5.7
Server Version: v1.23.14-eks-ffeb93d
```
- v1.12.1-eksbuild.2
- OS 
```NAME=Bottlerocket
ID=bottlerocket
VERSION="1.12.0 (aws-k8s-1.23)"
PRETTY_NAME="Bottlerocket OS 1.12.0 (aws-k8s-1.23)"
VARIANT_ID=aws-k8s-1.23
VERSION_ID=1.12.0
BUILD_ID=6ef1139f
HOME_URL="https://github.com/bottlerocket-os/bottlerocket"
SUPPORT_URL="https://github.com/bottlerocket-os/bottlerocket/discussions"
BUG_REPORT_URL="https://github.com/bottlerocket-os/bottlerocket/issues"
```
- Kernel `Linux ip-172-16-65-97.us-west-2.compute.internal 5.10.157 #1 SMP Wed Jan 25 03:35:19 UTC 2023 x86_64 GNU/Linux`

**Comment by jdn5126** [comment]
@mindw are you seeing the same behavior with other variables or just `ENABLE_PREFIX_DELEGATION`? I am not as familiar with terraform, but with a normal cluster, running the relevant `aws eks (create-addon|update-addon)` commands works as expected. Do you know what command `resource "aws_eks_addon" "vpc_cni"` maps to?

I don't think this has anything to do with VPC CNI, so we may need to move to https://github.com/terraform-aws-modules/terraform-aws-eks or managed addon team, but let's go through this exercise first.

Can you drop the `resource "aws_eks_addon" "vpc_cni"` section and manually run `aws eks create-addon` and see if you still have an issue?

**Comment by mindw** [comment]
@jdn5126 thank you for the quick reply!

Although it is tempting to look at Terraform as a potential culprit, it doesn't explain how the above API conflict with the cluster settings.

State of the rest of the values - of the four settings only `WARM_PREFIX_TARGET` has the wrong value (then again it is the only value which is different from pre-installed version, the rest are either missing or identical).

From the reference chart, docs and manifest it seems the previous "kubectl apply" resources were "adopted". Unfortunately "adopting" may lead to unexpected merge behaviour as described in https://github.com/helm/helm/issues/9958 .

Kubectl applied configuration extracted from the manifest:
```
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"DaemonSet","metadata":{"annotations":{},"labels":{"k8s-app":"aws-node"},"name":"aws-node","namespace":"kube-system"},"spec":{"selector":{"matchLabels":{"k8s-app":"aws-node"}},"template":{"metadata":{"labels":{"k8s-app":"aws-node"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/os","operator":"In","values":["linux"]},{"key":"kubernetes.io/arch","operator":"In","values":["amd64","arm64"]},{"key":"eks.amazonaws.com/compute-type","operator":"NotIn","values":["fargate"]}]}]}}},"containers":[{"env":[{"name":"ADDITIONAL_ENI_TAGS","value":"{}"},{"name":"AWS_VPC_CNI_NODE_PORT_SUPPORT","value":"true"},{"name":"AWS_VPC_ENI_MTU","value":"9001"},{"name":"AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER","value":"false"},{"name":"AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG","value":"false"},{"name":"AWS_VPC_K8S_CNI_EXTERNALSNAT","value":"false"},{"name":"AWS_VPC_K8S_CNI_LOGLEVEL","value":"DEBUG"},{"name":"AWS_VPC_K8S_CNI_LOG_FILE","value":"/host/var/log/aws-routed-eni/ipamd.log"},{"name":"AWS_VPC_K8S_CNI_RANDOMIZESNAT","value":"prng"},{"name":"AWS_VPC_K8S_CNI_VETHPREFIX","value":"eni"},{"name":"AWS_VPC_K8S_PLUGIN_LOG_FILE","value":"/var/log/aws-routed-eni/plugin.log"},{"name":"AWS_VPC_K8S_PLUGIN_LOG_LEVEL","value":"DEBUG"},{"name":"DISABLE_INTROSPECTION","value":"false"},{"name":"DISABLE_METRICS","value":"false"},{"name":"DISABLE_NETWORK_RESOURCE_PROVISIONING","value":"false"},{"name":"ENABLE_IPv4","value":"true"},{"name":"ENABLE_IPv6","value":"false"},{"name":"ENABLE_POD_ENI","value":"false"},{"name":"ENABLE_PREFIX_DELEGATION","value":"false"},{"name":"MY_NODE_NAME","valueFrom":{"fieldRef":{"fieldPath":"spec.nodeName"}}},{"name":"WARM_ENI_TARGET","value":"1"},{"name":"WARM_PREFIX_TARGET","value":"1"}],"image":"602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.10.1-eksbuild.1","livenessProbe":{"exec":{"command":["/app/grpc-health-probe","-addr=:50051","-connect-timeout=5s","-rpc-timeout=5s"]},"initialDelaySeconds":60,"timeoutSeconds":10},"name":"aws-node","ports":[{"containerPort":61678,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["/app/grpc-health-probe","-addr=:50051","-connect-timeout=5s","-rpc-timeout=5s"]},"initialDelaySeconds":1,"timeoutSeconds":10},"resources":{"requests":{"cpu":"25m"}},"securityContext":{"capabilities":{"add":["NET_ADMIN"]}},"volumeMounts":[{"mountPath":"/host/opt/cni/bin","name":"cni-bin-dir"},{"mountPath":"/host/etc/cni/net.d","name":"cni-net-dir"},{"mountPath":"/host/var/log/aws-routed-eni","name":"log-dir"},{"mountPath":"/var/run/aws-node","name":"run-dir"},{"mountPath":"/var/run/dockershim.sock","name":"dockershim"},{"mountPath":"/run/xtables.lock","name":"xtables-lock"}]}],"hostNetwork":true,"initContainers":[{"env":[{"name":"DISABLE_TCP_EARLY_DEMUX","value":"false"},{"name":"ENABLE_IPv6","value":"false"}],"image":"602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.10.1-eksbuild.1","name":"aws-vpc-cni-init","securityContext":{"privileged":true},"volumeMounts":[{"mountPath":"/host/opt/cni/bin","name":"cni-bin-dir"}]}],"priorityClassName":"system-node-critical","serviceAccountName":"aws-node","terminationGracePeriodSeconds":10,"tolerations":[{"operator":"Exists"}],"volumes":[{"hostPath":{"path":"/opt/cni/bin"},"name":"cni-bin-dir"},{"hostPath":{"path":"/etc/cni/net.d"},"name":"cni-net-dir"},{"hostPath":{"path":"/var/run/dockershim.sock"},"name":"dockershim"},{"hostPath":{"path":"/run/xtables.lock"},"name":"xtables-lock"},{"hostPath":{"path":"/var/log/aws-routed-eni","type":"DirectoryOrCreate"},"name":"log-dir"},{"hostPath":{"path":"/var/run/aws-node","type":"DirectoryOrCreate"},"name":"run-dir"}]}},"updateStrategy":{"rollingUpdate":{"maxUnavailable":"10%"},"type":"RollingUpdate"}}}
```
And pretty printed to yaml: 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations: {}
  labels:
    k8s-app: aws-node
  name: aws-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: aws-node
  template:
    metadata:
      labels:
        k8s-app: aws-node
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
      containers:
        - env:
            - name: ADDITIONAL_ENI_TAGS
              value: '{}'
            - name: AWS_VPC_CNI_NODE_PORT_SUPPORT
              value: "true"
            - name: AWS_VPC_ENI_MTU
              value: "9001"
            - name: AWS_VPC_K8S_CNI_CONFIGURE_RPFILTER
              value: "false"
            - name: AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG
              value: "false"
            - name: AWS_VPC_K8S_CNI_EXTERNALSNAT
              value: "false"
            - name: AWS_VPC_K8S_CNI_LOGLEVEL
              value: DEBUG
            - name: AWS_VPC_K8S_CNI_LOG_FILE
              value: /host/var/log/aws-routed-eni/ipamd.log
            - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
              value: prng
            - name: AWS_VPC_K8S_CNI_VETHPREFIX
              value: eni
            - name: AWS_VPC_K8S_PLUGIN_LOG_FILE
              value: /var/log/aws-routed-eni/plugin.log
            - name: AWS_VPC_K8S_PLUGIN_LOG_LEVEL
              value: DEBUG
            - name: DISABLE_INTROSPECTION
              value: "false"
            - name: DISABLE_METRICS
              value: "false"
            - name: DISABLE_NETWORK_RESOURCE_PROVISIONING
              value: "false"
            - name: ENABLE_IPv4
              value: "true"
            - name: ENABLE_IPv6
              value: "false"
            - name: ENABLE_POD_ENI
              value: "false"
            - name: ENABLE_PREFIX_DELEGATION
              value: "false"
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: WARM_ENI_TARGET
              value: "1"
            - name: WARM_PREFIX_TARGET
              value: "1"
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni:v1.10.1-eksbuild.1
          livenessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - -addr=:50051
                - -connect-timeout=5s
                - -rpc-timeout=5s
            initialDelaySeconds: 60
            timeoutSeconds: 10
          name: aws-node
          ports:
            - containerPort: 61678
              name: metrics
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /app/grpc-health-probe
                - -addr=:50051
                - -connect-timeout=5s
                - -rpc-timeout=5s
            initialDelaySeconds: 1
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 25m
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /host/var/log/aws-routed-eni
              name: log-dir
            - mountPath: /var/run/aws-node
              name: run-dir
            - mountPath: /var/run/dockershim.sock
              name: dockershim
            - mountPath: /run/xtables.lock
              name: xtables-lock
      hostNetwork: true
      initContainers:
        - env:
            - name: DISABLE_TCP_EARLY_DEMUX
              value: "false"
            - name: ENABLE_IPv6
              value: "false"
          image: 602401143452.dkr.ecr.us-west-2.amazonaws.com/amazon-k8s-cni-init:v1.10.1-eksbuild.1
          name: aws-vpc-cni-init
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
      priorityClassName: system-node-critical
      serviceAccountName: aws-node
      terminationGracePeriodSeconds: 10
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /opt/cni/bin
          name: cni-bin-dir
        - hostPath:
            path: /etc/cni/net.d
          name: cni-net-dir
        - hostPath:
            path: /var/run/dockershim.sock
          name: dockershim
        - hostPath:
            path: /run/xtables.lock
          name: xtables-lock
        - hostPath:
            path: /var/log/aws-routed-eni
            type: DirectoryOrCreate
          name: log-dir
        - hostPath:
            path: /var/run/aws-node
            type: DirectoryOrCreate
          name: run-dir
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
    type: RollingUpdate
``

About Terraform:
1. code can be found at https://github.com/hashicorp/terraform-provider-aws/blob/0d4fcb2844a4111af83c7fb5db2af2b1d956584a/internal/service/eks/addon.go#L155 . It maps to `CreateAddonWith Context).
2. CloudTrail logs confirm the CreateAddon was called with the above configuration and eventually completed.

Here's something surprising from today (2023-02-17) vpc-cni returned schema is described as belonging to `aws-ebs-csi-driver` 
 (`v1.12.2-eksbuild.1` and `v1.12.0-eksbuild.2` return the correct schema) for v1.21.1 (both builks):
 ```
$ aws eks describe-addon-configuration --addon-name vpc-cni --addon-version v1.12.1-eksbuild.2 --profile dev_il --region us-east-1 | jq .configurationSchema -r | jq .
{
  "$defs": {
    "extraVolumeTags": {
      "description": "Additional tags to be added to all EBS volumes",
      "patternProperties": {
        "^.*$": {
          "maxLength": 256,
          "minLength": 0,
          "pattern": "^[a-zA-Z0-9 _\\.:\\/=+\\-@]*$",
          "type": "string"
        }
      },
      "propertyNames": {
        "maxLength": 128,
        "minLength": 1,
        "pattern": "^[a-zA-Z0-9 _\\.:\\/=+\\-@]*$",
        "type": "string"
      },
      "type": "object"
    }
  },
  "$schema": "https://json-schema.org/draft/2019-09/schema",
  "additionalProperties": false,
  "description": "Configurable parameters of the AWS EBS CSI Driver",
  "properties": {
    "controller": {
      "additionalProperties": false,
      "properties": {
        "extraVolumeTags": {
          "$ref": "#/$defs/extraVolumeTags"
        }
      },
      "type": "object"
    },
    "node": {
      "additionalProperties": false,
      "properties": {
        "tolerateAllTaints": {
          "description": "Node pods will tolerate all taints",
          "type": "boolean"
        },
        "volumeAttachLimit": {
          "description": "Overrides the maximum number of volumes that can be attached per node (for all nodes)",
          "minimum": 0,
          "type": "integer"
        }
      },
      "type": "object"
    }
  },
  "type": "object"
}
```
