### ISSUE TITLE
dockershim is still in v1.12?

### ISSUE THREAD

**Issue by Chenjun-Shen** [aws/amazon-vpc-cni-k8s#2342]
**What happened**:

I found dockershim is still being used in v1.12. I thought it has been dropped in v1.12.

**Attach logs**

In the daemonsets yaml, following can be still seen.
```      
      - mountPath: /var/run/dockershim.sock
          name: dockershim
...
      - hostPath:
          path: /var/run/dockershim.sock
          type: ""
        name: dockershim
```
This image is being used.
```image: 602401143452.dkr.ecr.eu-central-1.amazonaws.com/amazon-k8s-cni-init:v1.12.6-eksbuild.1```

**What you expected to happen**:
dockershim is supposed to be removed in v1.12.

**How to reproduce it (as minimally and precisely as possible)**:
It's been seen in v1.12.6.

**Anything else we need to know?**:
Nothing

**Environment**:
- Kubernetes version (use `kubectl version`):
`
Client Version: v1.26.3
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
`
- CNI Version
```
v1.12.6-eksbuild.1
```
- OS (e.g: `cat /etc/os-release`):
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- Kernel (e.g. `uname -a`):
```
Linux ip-10-142-56-139.eu-central-1.compute.internal 5.4.231-137.341.amzn2.x86_64 #1 SMP Tue Feb 14 21:50:55 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
