### ISSUE TITLE
Make eniconfig az aware?

### ISSUE THREAD

**Issue by eisig** [aws/amazon-vpc-cni-k8s#238]
Maybe most of the time, we just want to config  all nodes in az1 to use subnet01,  az2 to use subnet02.
Can we make the ENIConfig az aware? so we can annotation all pods in the same asg to use the same ENIConfig.

the config can be something like: 
```
kind: ENIConfig
metadata:
 name: group1-pod-netconfig
spec:
  subnets: 
     - az: xx-east-01
       subnet: subnet-0c4678ec01ce68b24
     - az: xx-east-02
       subnet: subnet-xxx
   securityGroups:
```
