### ISSUE TITLE
Intermittent timeouts connecting to service in same EKS cluster via Internal NLB

### ISSUE THREAD

**Issue by thatInfrastructureGuy** [aws/amazon-vpc-cni-k8s#2505]
**What happened**:
We get intermittent timeouts when pinging services in EKS cluster. This only happens if the caller and callee are in the **_same EKS cluster and traffic goes through private NLB._** We have also noticed that this happens when caller pod is in the same AZ as private NLB IP, which is being hit.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a service with LoadBalancer. It should be private NLB.
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: whoami
  name: whoami
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  labels:
    app: whoami
  name: whoami
  namespace: whoami
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: whoami
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: whoami
spec:
  replicas: 5
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
      - image: traefik/whoami
        imagePullPolicy: IfNotPresent
        name: whoami
        ports:
        - containerPort: 80
          protocol: TCP
---
```

2. Wait for Loadbalancer to be _active_. Check AWS UI. 
3. Get all the IPs of private NLB. 
```bash
nslookup xxx-xyz.elb.us-west-2.amazonaws.com
Server:         x.x.x.x
Address:        x.x.x.x#53

Non-authoritative answer:
Name:   xxx-xyz.elb.us-west-2.amazonaws.com
Address: 10.2.x.x  # us-west-2a
Name:   xxx-xyz.elb.us-west-2.amazonaws.com
Address: 10.2.y.y # us-west-2b
Name:   xxx-xyz.elb.us-west-2.amazonaws.com
Address: 10.2.z.z # us-west-2c
```

4. On the **same** cluster run your client
```bash
kubectl run mysh --rm -i --tty --image alpine -- sh
/ # IP=10.2.x.x
/ # while true; do wget -O - -q -T 5 http://$IP/bench; sleep 0.5; done

/ # IP=10.2.y.y
/ # while true; do wget -O - -q -T 5 http://$IP/bench; sleep 0.5; done

/ # IP=10.2.z.z
/ # while true; do wget -O - -q -T 5 http://$IP/bench; sleep 0.5; done
```

5. At this point, **one of the IPs** should give you intermittent timeouts. If so, please open a second terminal and check if pod is hosted on same AZ as the NLB IP which is having the issue. 
```bash
kubectl get pods mysh -o=jsonpath='{.status.hostIP}'
```

**Anything else we need to know?**:
* We installed Cilium and still faced the same issue. The root cause seems to be NLB IP on the same AZ is having trouble reaching EKS NodePort, hence the internal pod network be it Cilium or AWS CNI does not seem to matter.

**Environment**: EKS
- Kubernetes version (use `kubectl version`): 1.27 (Tried 1.22 and 1.27)
- CNI Version: Tried default and latest
