### ISSUE TITLE
What is the purpose of the nodeagent sidecar if the network policy controller is disabled?

### ISSUE THREAD

**Issue by yurrriq** [aws/amazon-vpc-cni-k8s#2565]
**What happened**:

Given the following config...

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
data:
  enable-network-policy-controller: "true"
```

... the sidecar is still installed.

```yaml
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aws-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - args:
            - --enable-network-policy=false
          name: aws-eks-nodeagent
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.24.16-eks-2d98532
- CNI Version: v1.14.1-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.6 LTS 
- Kernel (e.g. `uname -a`): 5.15.0-1044-aws
