### ISSUE TITLE
Except doesn't work in Egress ipBlock

### ISSUE THREAD

**Issue by wiseelf** [aws/amazon-vpc-cni-k8s#2580]
**What happened**:
I'm trying to block egress access from all pods in a particular namespace to everything except the internet. To achieve that I created this yaml:
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: test-ns
spec: {}
status: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: test-ns
  name: deny-from-other-namespaces
spec:
  podSelector:
    matchLabels:
  ingress:
    - from:
        - podSelector: {}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: test-ns
  name: allow-internet-only
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test
  name: test
  namespace: test-ns
spec:
  containers:
    - args:
        - sleep
        - infinity
      image: alpine
      name: test
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

In theory that should block egress traffic to all internal cluster resources except coredns for DNS name resolution and internet access basically. But here is the result of applying that:

```
$ k -n test-ns exec -ti test -- ash
/ # curl kube-eagle.monitoring.svc.cluster.local:8080/metrics | tail -n 2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  828k    0  828k    0     0  4596k      0 --:--:-- --:--:-- --:--:-- 4601k
promhttp_metric_handler_requests_total{code="500"} 0
promhttp_metric_handler_requests_total{code="503"} 0
/ # curl ldap.mydomain.com:636 -vvv
*   Trying 10.5.1.16:636...
* Connected to ldap.mydomain.com (10.5.1.16) port 636
```

**Environment**:
- Kubernetes version (use `kubectl version`): Server Version: v1.27.4-eks-2d98532
- CNI Version: v1.15.0-eksbuild.2
- OS (e.g: `cat /etc/os-release`):  bottlerocket ```$ cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"```
- Kernel (e.g. `uname -a`):  ```Linux ip-10-1-193-17.ec2.internal 5.15.128 #1 SMP Thu Sep 14 21:42:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```
