### ISSUE TITLE
NetworkPolicy not applying exception to Egress rule

### ISSUE THREAD

**Issue by treyhyde** [aws/amazon-vpc-cni-k8s#2592]
**What happened**:

We have a network policy to disallow access to the cluster (IP ranges changed) but allow to the internet.   Effectively an untrusted workload.

```
egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 192.168.0.0/24
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
```

The allow portion of this takes effect but it also does not block the items in the except list.
This was working as desired under Calico.  This seems like the only rule we have with the behavior difference between calico and `vpc-cni-k8s` and as such unable to proceed with the migration.

**Attach logs**

^^ this appears to not exist in the official containers.

**What you expected to happen**:
The "except" range to be blocked.

**How to reproduce it (as minimally and precisely as possible)**:
Apply the network policy

**Anything else we need to know?**:

**Environment**:
EKS
Client Version: v1.28.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.4-eks-2d98532
Bottlerocket OS 1.15.0 (aws-k8s-1.27)   5.15.128
