### ISSUE TITLE
Hardcoded ConfigMap name: amazon-vpc-cni

### ISSUE THREAD

**Issue by ppodbielski** [aws/amazon-vpc-cni-k8s#2612]
**What happened**:
In chart ConfigMap name is hardcoded to `amazon-vpc-cni`: https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/configmap.yaml#L15

This causes problems if two helmreleases of `aws-vpc-cni` are deployed in the same namespace with different names.

Source: https://github.com/aws/amazon-vpc-cni-k8s/pull/2517/files#diff-667ab2d37d1d54a8c53c92c0ed8544837ff52bc8cb4620ee1bc3d42135bf2f8e in V1.14 

**What you expected to happen**:
ConfigMap name should be configurable, e.g: `amazon-{{ include "aws-vpc-cni.fullname" . }}`

**How to reproduce it (as minimally and precisely as possible)**:
deploy 2 helmreleases of `aws-vpc-cni` in the same namespace with different names

**Environment**:
- CNI Version 1.14

**Comment by jdn5126** [comment]
@ppodbielski I am confused, why would there be two helm releases of `aws-vpc-cni` in the same namespace with different names? The error you are talking about sounds like it would happen with any kubernetes resource

**Comment by ppodbielski** [comment]
@jdn5126 
In my configuration, I have 6 subnets and 3AZ. Due to known limitations:
```
AWS CNI does not support adding a second subnet for the same AZ. ENIConfig only allows setting up 1 subnet and here is the upstream issue to add additional subnets but stale for a long time ENI Config Label/Annotation Def Concatenation aws/amazon-vpc-cni-k8s#1207
```
To workaround this problem I deployed 2 `vpc-cni` HR in the same namespace. It works for me till now

**Comment by jkotiuk** [comment]
If I want to use fullname `amazon-vpc-cni`, the other configmap will have the same name as the one added in 1.14, which will lead to a conflict.

```
helm template amazon-vpc-cni eks/aws-vpc-cni --set cniConfig.enabled=true --set fullnameOverride=amazon-vpc-cni | grep ConfigMap -A 2
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
--
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
```

IMO this is just bad practice to hardcode resource name

**Comment by jdn5126** [comment]
@ppodbielski I am not sure how two VPC CNI installations could work, but for the ENIConfig enhancement, this is a task that we are currently working on. I am also curious why you are using the first ConfigMap to begin with. That ConfigMap is used for overriding the conflist, and it requires `Values.cniConfig.enabled` to be set to even be rendered. If you want to continue with this double installation, and you need the first ConfigMap for some reason, can you set `fullnameOverride` (https://github.com/aws/amazon-vpc-cni-k8s/blob/master/charts/aws-vpc-cni/templates/_helpers.tpl#L14)?

@jkotiuk a fixed name is required so that controllers know which ConfigMap they need to watch. For the first ConfigMap, which is used to override the conflist, that's why `Values.fullnameOverride` is provided.

**Comment by ppodbielski** [comment]
@jdn5126 
My configuration (each release has its own set of nodes to launch):

release:
```
  fullnameOverride: "aws-node"
  eniConfig:
    create: true
    region: AWS_REGION
    subnets:
      pods-subnet-1a:
        id: PODS_SUBNET_A
        securityGroups:
          - POD_SG
      pods-subnet-1b:
        id: PODS_SUBNET_B
        securityGroups:
          - POD_SG
      pods-subnet-1c:
        id: PODS_SUBNET_C
        securityGroups:
          - POD_SG
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "NodeA"
                  operator: In
                  values:
                    - "true"
                    
```

release1:
```
  fullnameOverride: "aws-node-1"
  eniConfig:
    create: true
    region: AWS_REGION
    subnets:
      pods-subnet-1a:
        id: PODS_SUBNET_1
        securityGroups:
          - POD_SG
      pods-subnet-1b:
        id: PODS_SUBNET_2
        securityGroups:
          - POD_SG
      pods-subnet-1c:
        id: PODS_SUBNET_3
        securityGroups:
          - POD_SG
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: "NodeA"
                  operator: NotIn
                  values:
                    - "true"
```
