### ISSUE TITLE
Pod communication issues when applying network policies on AWS VPC-CNI

### ISSUE THREAD

**Issue by AlexanderPavlovHC** [aws/amazon-vpc-cni-k8s#2652]
**What happened**:
After switching from Calico to native AWS VPC-CNI and adding a network policy to restrict access, some of the new pods that are created to run jobs are encountering a **Crashloopbackoff** error and are unable to complete their tasks. No such errors were observed when using Calico.

Details:

- The policy allows access for haproxy, prometheus, elasticsearch, and intra-namespace pod communication.
- Pod communication issues arose after switching from Calico to AWS VPC-CNI.
- **Network policy manifest:**
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-policies
  namespace: default
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: elastic-system
          podSelector:
            matchLabels:
              app.kubernetes.io/instance: eck-operator
      ports:
        - port: 9200
        - port: 9300
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: haproxy-ingress
          podSelector:
            matchLabels:
              app.kubernetes.io/name: haproxy-ingress
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: prometheus
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - port: 8080
        - port: 9090
        - port: 9091
        - port: 9253
        - port: 15692
    - from:
        - podSelector: {} 
```

**Network policy diagram:**

<img width="1206" alt="Screenshot 2023-11-03 at 15 46 47" src="https://github.com/aws/amazon-vpc-cni-k8s/assets/97234680/a6e2a1ed-326f-4b4e-9d91-214148b31976">

**Logs from network-policy-agent.log:**
```
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Target Pod doesn't belong to the current pod Identifier: ","Name: ":"ledger-cron-15-28315500-fl5np","Pod ID: ":"ledger-cron-15-28315510-default"}
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Processing Pod: ","name:":"docx-api-5c84697988-l8f49","namespace:":"default","podIdentifier: ":"ledger-cron-15-28315510-default"}
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Target Pod doesn't belong to the current pod Identifier: ","Name: ":"docx-api-5c84697988-l8f49","Pod ID: ":"ledger-cron-15-28315510-default"}
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Processing Pod: ","name:":"qmt-poland-motor-generali-worker-77d67fb98-zwp2w","namespace:":"default","podIdentifier: ":"ledger-cron-15-28315510-default"}
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Target Pod doesn't belong to the current pod Identifier: ","Name: ":"qmt-poland-motor-generali-worker-77d67fb98-zwp2w","Pod ID: ":"ledger-cron-15-28315510-default"}
{"level":"info","ts":"2023-11-02T13:10:35.224Z","logger":"controllers.policyEndpoints","caller":"controllers/policyendpoints_controller.go:149","msg":"Processing Pod: ","name:":"ledger-cron-15-28315490-9nbrf","namespace:":"default","podIdentifier: ":"ledger-cron-15-28315510-default"}
```

**Environment**:

- Kubernetes: 1.25
- Kubelet: v1.25.12-eks-8ccc7ba
- VPC-CNI add-on: v1.15.1-eksbuild.1
- AMI release: 1.25.12-20230825
- Kernel: 5.10.186-179.751.amzn2.x86_64
