### ISSUE TITLE
CNI eniConfig do not update already created ENI with new list of SGs

### ISSUE THREAD

**Issue by md2k** [aws/amazon-vpc-cni-k8s#277]
Hi all, i'm testing custom network configuration where Pods using separate networks, and i found that CNI plugin seems do not update SGs for interfaces.
for example.
We create subnet with single SG group
```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eu-west-1a
spec:
  subnet: subnet-03f4d3783ec39ba1b
  securityGroups:
    - sg-0dd2e41f172c02b81
```
i can see that new ENI attached with desired subnet and security group.
As next step we update eniConfig resource to:
```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
  name: eu-west-1a
spec:
  subnet: subnet-03f4d3783ec39ba1b
  securityGroups:
    - sg-0dd2e41f172c02b81
    - sg-0732b09bb104c29fe
    - sg-0e8274e729e84a5c2
```
In CNI logs i can see that CNI plugin got updated configuration from CRD resource, but attached interfaces do not get updated list of SGs.
As result we need :
* update already created and attached eni manually
* terminate worker

While we can predefine couple of SGs during cluster creation and later add rules inside created SGs, it will be more efficient to have ability update them over eniConfig resources.
