### ISSUE TITLE
Make the eniconfig name as string in the template.

### ISSUE THREAD

**Issue by orsenthil** [aws/amazon-vpc-cni-k8s#2990]
When an ENIConfig with name is given a number, instead of string,

```
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
    name: 3
    namespace: kube-system
spec:
    securityGroups:
        - sg-xx
        - sg-xx2
    subnet: subnet-xxx
```

the helm chart apply throws an error stating

```
unable to ssa object &{Object:map ... } ... name is required

```

We have to make the eniconfig name as string in the template.

https://github.com/aws/amazon-vpc-cni-k8s/blob/e8faf2f87615a70f8319d6fdf4df8324ffa4cc20/charts/aws-vpc-cni/templates/eniconfig.yaml#L6
