### ISSUE TITLE
Egress rule with /12 ignored but changing to /16 made it work

### ISSUE THREAD

**Issue by KyronSr** [aws/amazon-vpc-cni-k8s#3034]
I am running JupyterHub in my EKS cluster with the vpc cni enabled.  It was working just fine but during a security review, I noticed that my notebooks were able to access parts of my cluster which I was not expecting.  I reviewed the JupyterHub helm chart and they have a fairly extensive set of network policies which should block access but was not.  Here is the relevant portion of the egress network policy to which I've narrowed down the problem:

```
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
              - 169.254.169.254/32
``` 

Seemed entirely reasonable to me but I attempted to access a specific 172.16 IP address (which feel well within the /12) and it was able to access it (which it should not have).  Here is an example of the log showing the "ACCEPT"

```
Node: ip-172-16-13-210.ec2.internal;SIP: 172.16.13.157;SPORT: 46176;DIP: 172.16.13.133;DPORT: 8080;PROTOCOL: TCP;PolicyVerdict: ACCEPT
```

After much fiddling around with it, I found out if I changed the /12 to a /16 it would properly deny:

```
Node: ip-172-16-13-210.ec2.internal;SIP: 172.16.13.157;SPORT: 52518;DIP: 172.16.13.133;DPORT: 8080;PROTOCOL: TCP;PolicyVerdict: DENY
```

To resolve the problem (without editing the underlying helm file for JupyterHub) was to add in a new network policy:

```
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 172.16.0.0/16
  policyTypes:
    - Egress
```

With this policy in place, it is properly denying access to the 172 resources as I would expect.  I couldn't see anything in the help, etc. which specifically mentions limitations on the net mask but most examples are /16 in all the Go code.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.30.3-eks-a18cd3a
- CNI Version: v1.18.3-eksbuild.3
- OS (e.g: `cat /etc/os-release`):  BottleRocket - amazon/bottlerocket-aws-k8s-1.30-x86_64-v1.22.0-b6684b72
- Kernel (e.g. `uname -a`):
