### ISSUE TITLE
Why doesn't AWS CNI support service port translation for network policies?

### ISSUE THREAD

**Issue by charles-large** [aws/amazon-vpc-cni-k8s#3181]
In the AWS documentation, within the considerations section for using network policies, the following requirement is listed.

"For any of your Kubernetes services, the service port must be the same as the container port. If you’re using named ports, use the same name in the service spec too." [Doc Link](https://docs.aws.amazon.com/eks/latest/userguide/cni-network-policy.html)

What are the reasons, technical or not, that network policies on the AWS CNI require this and don't support the usual Kubernetes service port translation (service has differing port it listens on than target port of container) 

Example:

This configuration, based on the documentation, would not be supported with AWS CNI network policies. The service is listening on port 80, but the targetport points to container on port 8080.

```
apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  ports:
  - name: http                   
    port: 80                  -> this port should match
    targetPort: 8080          -> this port should match
  selector:
    app: test-app
---
apiVersion: v1
kind: Pod
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  containers:
  - name: test-app
    image: test-app-image
    ports:
    - name: http              
      containerPort: 8080     -> this port should match
```
