### ISSUE TITLE
Memory Leak in 1.19.3-eksbuild.1

### ISSUE THREAD

**Issue by rocktavious** [aws/amazon-vpc-cni-k8s#3233]
**What happened**:
Yesterday we upgraded several of our clusters VPC CNI from 1.19.2-eksbuild.5 to 1.19.3-eksbuild.1 and it appears that version has a memory leak.  After we noticed this we rolled back the update and the memory leak is no longer happening.

**Attach logs**
![Image](https://github.com/user-attachments/assets/c5b02d64-588c-46c0-8ca7-dd16de922d13)
![Image](https://github.com/user-attachments/assets/1e8969c6-4f75-4ad1-a353-5b3f95978aef)
![Image](https://github.com/user-attachments/assets/d98db193-4035-4e0f-bffd-6dff41bda94c)

**What you expected to happen**:

To not see runaway memory usage

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to latest version

**Anything else we need to know?**:

I've created a support case too: 174180492200248

**Environment**:
- Kubernetes version (use `kubectl version`): v1.31.5-eks-8cce635
- CNI Version: 1.19.3-eksbuild.1
- OS (e.g: `cat /etc/os-release`): Amazon Linux 2023.6.20250218
- Kernel (e.g. `uname -a`): 6.1.128-136.201.amzn2023.x86_64

**Comment by jayanthvn** [comment]
Thanks, we are actively investigating this issue.

**Comment by Pavani-Panakanti** [comment]
@rocktavious Did you upgrade both NP agent and CNI versions ? what are the versions of CNI image and NP agent image during this upgrade window ?
We are not able to reproduce memory leak on our end. Can you please collect node logs using this script https://github.com/awslabs/amazon-eks-ami/blob/main/log-collector-script/linux/README.md and send the node log bundle to "k8s-awscni-triage@amazon.com". Thanks

**Comment by rocktavious** [comment]
@Pavani-Panakanti - This is happening in multiple clusters that have upgraded now.  For the upgrade we are just using the terraform module for EKS - https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest


![Image](https://github.com/user-attachments/assets/d43f34cc-8902-4ea9-ae37-baade094390b)

![Image](https://github.com/user-attachments/assets/2fd40eff-105b-460a-9641-19406397e390)

**Comment by jaydeokar** [comment]
Just to confirm, are you using Network Policy agent in the cluster? Do you have more enhanced metrics that track against containers in aws-node pod ?
  
Also, if you could you give us a little insights into the workloads that run on this cluster, that would help. Do you launch standalone pods against which you create network policies ?

**Comment by rocktavious** [comment]
@jaydeokar yes we use 2 network policies
```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-egress
  namespace: runner-jobs
  annotations:
    kubernetes.io/description: "Deny all egress traffic, permitted elsewhere."
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-from-runner-only
  namespace: runner-jobs
  annotations:
    kubernetes.io/description: "Allow ingress traffic from runner pods only"
spec:
  podSelector:
    matchLabels:
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 172.22.0.0/19
        - 172.22.32.0/19
        - 172.22.64.0/19
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          deploys-opslevel-runner: "true"
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: runner
          app.kubernetes.io/part-of: opslevel
  - from:
    - namespaceSelector:
        matchLabels:
          deploys-opslevel-runner: "true"
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: runner-faktory
          app.kubernetes.io/part-of: opslevel
```

Then we have a custom workload we built that interfaces with the kubernetes API to spin up a pod (as a execution context for an async job) in which a job is run and then the pod is shutdown after job completion.  So if i understand what you are getting at - this workload would be causing alot of churn for `aws-node` in terms of pods targeted by these network policies.
