### ISSUE TITLE
Ramdomize SNAT not working

### ISSUE THREAD

**Issue by InAnimaTe** [aws/amazon-vpc-cni-k8s#407]
Sans me possibly doing this wrong, I've made the variable exist to enable randomization for snat rules, but I'm not seeing this being applied in the iptables rules (when running `iptables-save` from a `aws-node` pod via `kubectl exec -it aws-node-pvx48 /bin/sh -n kube-system`). When I edit the daemonset, the pods re-roll but nothing seems to change (let me know if I'm doing this wrong).

```
sh-4.2# env | grep CNI
AWS_VPC_K8S_CNI_LOGLEVEL=DEBUG
AWS_VPC_K8S_CNI_RANDOMIZESNAT=hashrandom
```

```
sh-4.2# iptables-save | grep random
-A KUBE-SVC-ERIFXISQEP7F7OF4 -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-AL73UYBXEM4ASRGB
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-7GVY2H3HQJW2S663
-A KUBE-SVC-TCOU7JCQXEZGVUNU -m statistic --mode random --probability 0.50000000000 -j KUBE-SEP-JLDNAEVHEO37WMGP
```

Full `iptables-save` can be found [here](https://hackmd.io/yfk6ZpgsSu6HFvHi-3HFJA). Also tried with `prng` but then realized iptables in only version 1.4; interested as to if that could be increased or if there's a newer version I can use.

Thanks!

**Comment by InAnimaTe** [comment]
@taylorb-syd @mogren any insight would be appreciated!

**Comment by taylorb-syd** [comment]
Hi there, @InAnimaTe, first, can we get your clusters CNI version to confirm if you're running a compatible version:

```
kubectl describe daemonset aws-node --namespace kube-system | grep Image | cut -d "/" -f 2
```

Next, can you also confirm if you refreshed your workers after adding the environment variable to the DaemonSet? I outlined this limitation in PR #246 [here](https://github.com/aws/amazon-vpc-cni-k8s/pull/246#issuecomment-452266013).

**Comment by InAnimaTe** [comment]
Here's what the daemonset looks like:

```
      containers:
      - env:
        - name: AWS_VPC_K8S_CNI_RANDOMIZESNAT
          value: hashrandom
        - name: AWS_VPC_K8S_CNI_LOGLEVEL
          value: DEBUG
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/amazon-k8s-cni:v1.3.2
```

I have not rebooted the worker nodes yet. Let me work on that now and see what I've got after that! In any case, if rebooting is necessary, the docs should be updated to reflect this; I can make that PR.
