### ISSUE TITLE
set ENI_CONFIG_LABEL_DEF to failure-domain.beta.kubernetes.io/zone not work

### ISSUE THREAD

**Issue by xvdy** [aws/amazon-vpc-cni-k8s#611]
# Question
I build an cluster on ec2 and use amazon-vpc-cni-k8s as cni plugin, But when I create a pod, it cant gain an ip. 

# Environment
k8s version:v1.13.2
cni version: amazon-vpc-cni-k8s:v1.5.3

I set `AWS_VPC_K8S_CNI_CUSTOM_NETWORK_CFG: "true"` and `ENI_CONFIG_LABEL_DEF:failure-domain.beta.kubernetes.io/zone`, and then create eniConfig for each available zone like this

```
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-south-1a
spec:
  securityGroups:
  - sg-6953xxxx
  subnet: subnet-0de8838bc5072xxxx
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-south-1b
spec:
  securityGroups:
  - sg-6953xxxx
  subnet: subnet-0fb2a0cb71f99xxxx
---
apiVersion: crd.k8s.amazonaws.com/v1alpha1
kind: ENIConfig
metadata:
 name: ap-south-1c
spec:
  securityGroups:
  - sg-6953xxxx
  subnet: subnet-02bc53365ae50xxxx
```

# Logs
I found some clues in ipamd.log.
```
2019-09-06T06:39:20.662Z [ERROR]        Failed to get pod ENI config
```
```
2019-09-06T06:00:02.479Z [INFO] Handle corev1.Node: node01.awsind, map[kubeadm.alpha.kubernetes.io/cri-socket:/var/run/dockershim.sock node.alpha.kubernetes.io/ttl:0 volumes.kubernetes.io/controller-managed-attach-detach:true], map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/os:linux kubernetes.io/hostname:node01.awsind]
2019-09-06T06:00:02.479Z [INFO] Setting myENI to: default
```
It seems that the ipam didn't find the right eniConfig and then pick default,but unfortunately I did't set an eniConfig with name default.
