### ISSUE TITLE
Add kustomization.yaml

### ISSUE THREAD

**Issue by jwenz723** [aws/amazon-vpc-cni-k8s#642]
I am trying to install the AWS VPC CNI with [CNI Custom Networking](https://docs.aws.amazon.com/en_pv/eks/latest/userguide/cni-custom-network.html) feature enabled. I would like to be able to create a kustomize patch and apply it to the [config/v1.5/aws-k8s-cni.yaml](https://github.com/aws/amazon-vpc-cni-k8s/blob/master/config/v1.5/aws-k8s-cni.yaml) file without having to copy and paste the config/v1.5/aws-k8s-cni.yaml file into my repo (so that no one can make modifications to it from my org).

There is a way to accomplish this using the go-getter generator plugin as described [here](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/goGetterGeneratorPlugin.md#use-non-kustomize-remote-sources), but it would be nicer if the amazon-vpc-cni-k8s repo just contained a kustomization.yaml file so it could be referenced directly as a kustomize base/resource without the need for a custom generator plugin. 

This would allow for my kustomization.yaml file to look something like this to apply my patch for CNI Custom Networking:

```yaml
patchesStrategicMerge:
  - aws-node-patch.yaml

resources:
- github.com/aws/amazon-vpc-cni-k8s//config/v1.5?ref=v1.5.4 // this assumes that there is a kustomization.yaml file within the config/v1.5 directory
```
