### ISSUE TITLE
feature request: floating IP

### ISSUE THREAD

**Issue by sergey-safarov** [aws/amazon-vpc-cni-k8s#652]
We use SIP servers in kubernetes environment.
Because many VoIP carriers and customers use firewall rules we cannot place (create) new call and route this via specific IP address as source IP:
1. new outbound `TCP` connection cannot be send via Application Load Balancer (ALB);
1. new outbound `UDP` or `TCP` connection cannot be send via Network Load Balancer (ALB);
1. elastic IP cannot be assigned to Kubernetes resource;

Also we use SIP peers via VPN connections and faced with same issue. We cannot assign static IP pod directly or via statefulset resource. Reason kubernetes does not support static IP.

More details and discussion with **Tim Hockin** you can find at https://github.com/kubernetes/kubernetes/issues/80122

Static IP support may be changed in kubernetes future releases, but not now.
Could you add support plugin API endpoint that i may call to assign/release specific IP to one of available `eni` interfaces. And mark this IP as not assignable to pods.
Later i will configure this IP on node 'ethX' interface as secondary IP address and start new container on this node with `host` network.

**Optionaly**
May be possible to parse `statefulset` annotation like
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kamailio
  annotations:
    private_ip_pool: "172.21.0.16 172.21.1.16 172.21.2.16 172.21.3.16"
```
And assign private IP addresses from `private_ip_pool` annotation to new created pods.
