### ISSUE TITLE
Automate load testing

### ISSUE THREAD

**Issue by jaypipes** [aws/amazon-vpc-cni-k8s#691]
Currently, we run load testing manually before a release, following these rough steps:

1. create a 3 node cluster
1. scale pod replica from 0 to 130
1. verify kubectl get deployment all to available
1. scale replica from 130 to 0
1. verify kubectl get deployment 
1. repeat 2 to 5 for at least 3 times

with this sample Deployment:

```yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker-hello
spec:
  selector:
    matchLabels:
      app: worker-hello
      tier: backend
      track: stable
  replicas:  10
  template:
    metadata:
      labels:
        app: worker-hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: worker-hello
          image: golang:1.10-alpine
          command:
            - sleep
            - "3600"
```

- [ ] Place above test steps into a Bash script that can exercise the CNI plugin
- [ ] Automatically execute load test on each merge
- [ ] Add job that stores timing/results in a data store and allows for storing regression history
