### ISSUE TITLE
Problem with Prometheus Service Discovery after release 1.5.5

### ISSUE THREAD

**Issue by stafot** [aws/amazon-vpc-cni-k8s#720]
Ref. [kube-prometheus: CoreDNSDown
](https://github.com/coreos/prometheus-operator/issues/2278#issuecomment-553824661)

It seems that with version 1.5.5 is introduced a bug that breaks service Discovery of Prometheus Monitor of CoreDNS. 
With version `1.5.3` Definition that works
```yaml
 apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
``` 
The above definition breaks with version `1.5.5` 
To fix the issue the definition refactored as following.
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: coredns
  name: coredns
  namespace: monitoring
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    targetPort: 9153
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kube-dns
      eks.amazonaws.com/component: kube-dns
```
I am reporting here also because it looks as a possible networking change that might affect other services/operators too. 

If you need more info I am glad to help.

Cluster Info: `AWS EKS 1.14.7`
