### ISSUE TITLE
EKS cluster: Container inside POD have no internet access

### ISSUE THREAD

**Issue by bakuppus** [aws/amazon-vpc-cni-k8s#736]
Issue: EKS cluster: Container inside POD have no internet access

Impact: PR# yum install httpd -y  not able to install any packages due to no internet access

Issue explained:

Building [bakuppus/amazonlinux-httpd-dockerfile]...
Sending build context to Docker daemon  2.048kB

Step 1/8 : FROM amazonlinux:latest
 ---> 6ef285e58e33
Step 2/8 : RUN cat /etc/resolv.conf
 ---> Using cache
 ---> 972fe779e9f0
Step 3/8 : RUN echo  " "
 ---> Running in 00a80dde5c0f
 
 ---> 319a0d4492c0
Step 4/8 : RUN yum install httpd -y
 ---> Running in 8684164ef36d
Loaded plugins: ovl, priorities
[91m

 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: amzn2-core/2/x86_64
[0mCould not retrieve mirrorlist http://amazonlinux.default.amazonaws.com/2/core/latest/x86_64/mirror.list error was
14: curl#6 - "Could not resolve host: amazonlinux.default.amazonaws.com"
time="2019-11-28T03:02:49Z" level=fatal msg="build failed: build failed: building [bakuppus/amazonlinux-httpd-dockerfile]: build artifact: unable to stream build output: The command '/bin/sh -c yum install httpd -y' returned a non-zero code: 1"

**Comment by jaypipes** [comment]
So you are building a container image from within a container running on one of your EKS worker nodes? Is that correct? You would need to provide us some information about the container that the build script is running in, and sharing the build script itself would be useful.

**Comment by mogren** [comment]
@bakuppus Any update on this issue?

**Comment by gimpiron** [comment]
Hey, I am facing the same issue here.
Yes, trying to build Docker image from within a container running on my EKS worker.
The only solution that works for me is appending --network=host to the build commands.
Is there a configuration option from EKS side?

**Comment by BlackRider97** [comment]
@mogren  @gimpiron  any possible resolution ? 
I am also facing this issue. 
`--network=host` complicates other K8s services discovery so not a good choice.

**Comment by andrewwebber** [comment]
Also having trouble with this with [Gitlab Kubernetes CI Executor](https://docs.gitlab.com/runner/executors/kubernetes.html) [

**Comment by gimpiron** [comment]
I have added this section to my eksctl file (that i use to create the cluster)

```
nodeGroups:
  - name: blablabla
    instanceType: m5.2xlarge
    preBootstrapCommands:
      # Replicate what --enable-docker-bridge does in /etc/eks/bootstrap.sh
      # Enabling the docker bridge network. We have to disable live-restore as it
      # prevents docker from recreating the default bridge network on restart
      - "cp /etc/docker/daemon.json /etc/docker/daemon_backup.json"
      - "echo -e '.bridge=\"docker0\" | .\"live-restore\"=false' >  /etc/docker/jq_script"
      - "jq -f /etc/docker/jq_script /etc/docker/daemon_backup.json | tee /etc/docker/daemon.json"
      - "systemctl restart docker"
```

Im pretty sure that it was that section that solved my problem (well, it was long time ago)
