### ISSUE TITLE
Run aws-node as unprivileged pod

### ISSUE THREAD

**Issue by mogren** [aws/amazon-vpc-cni-k8s#796]
We currently set the `aws-node` pod to be `privileged`, but that might not be needed.

Check if  `CAP_NET_ADMIN` and `CAP_DAC_OVERRIDE` is enough to set the RDF check to loose and copy the binary and config file:

https://github.com/aws/amazon-vpc-cni-k8s/blob/1ee59a06c597c62aa93e85fc1d2eedef553707a3/pkg/networkutils/network.go#L233-L246

**Comment by mogren** [comment]
Unfortunately, having the capabilities limited to `["NET_ADMIN", "DAC_OVERRIDE"]` is not enough to write to `/proc/sys/net/*`.  From the logs:
```
[DEBUG] Setting RPF for primary interface: /proc/sys/net/ipv4/conf/eth0/rp_filter
[ERROR] Failed to set up host networkfailed to configure eth0 RPF check: open /proc/sys/net/ipv4/conf/eth0/rp_filter: read-only file system
[ERROR] Initialization failure: ipamd init: failed to set up host network: failed to configure eth0 RPF check: open /proc/sys/net/ipv4/conf/eth0/rp_filter: read-only file system
```

**Comment by SaranBalaji90** [comment]
There are few ways to achieve this,

1) Set the rp_filter through init container.
```
    initContainers:
      - command:
        - sh
        - -c
        - sysctl net.ipv4.conf.eth0.rp_filter=2
        image: golang:1.13-stretch
        name: rp_filter_setting
        securityContext:
          privileged: true
```
2) Set the rp_filter when the ec2 instance starts up. But the problem with this approach is, if anyone builds custom AMI then they have to make sure this change is added to their AMI build scripts.
3) Enabling unsafe sysctl - https://kubernetes.io/docs/tasks/administer-cluster/sysctl-cluster/#enabling-unsafe-sysctls but this doesn't help us, because https://github.com/kubernetes/kubernetes/blob/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/pkg/kubelet/sysctl/whitelist.go#L89 kubelet rejects the pod allocation when net.* sysctl is used along with host network. 

This leave us with option-1 being more suitable for our usecase.

Proposed solution:
1) Add a flag that instructs aws-node pod whether to perform or skip setting rp_filter value for eth0.
2) Add init container as described above and remove "privileged"  mode for aws-node.
3) At later time, deprecate the flag and remove it completely from aws-node.
