### ISSUE TITLE
Calico Pod Network Policies not working for Windows workloads 

### ISSUE THREAD

**Issue by niranjan94** [aws/amazon-vpc-cni-k8s#861]
I'm trying to block pods from accessing the instance metadata service on an EKS Cluster using Calico and the following `GlobalNetworkPolicy`.

```yaml
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: block-metadata-service
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector: "has(projectcalico.org/namespace) && projectcalico.org/namespace not in {'efs-provisioner', 'kube-system'}"
  egress:
    - action: Allow
      destination:
        notNets:
          - 169.254.169.254/32
  types:
    - Egress
```

The network policy is working as expected with Linux pods, but not working with windows pods. Windows pods are still able to access the metadata service. 

Is there anything extra that needs to be done for windows ? 
Or is this not supported at all for windows ?

Thanks in advance :)
