### ISSUE TITLE
Calico config is using deprecated node selector.

### ISSUE THREAD

**Issue by Gmagella** [aws/amazon-vpc-cni-k8s#867]
Looking at AWS instructions on how to install calico on EKS [here](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) its pointing to amazon-vpc-cni-k8s/release-1.5/config/v1.5/calico.yaml which have the node selector as such:
`kind: DaemonSet
...
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux`
Which is deprecated, and should be replaced to 
`kind: DaemonSet
...
    spec:
      nodeSelector:
        kubernetes.io/os: linux`

**Comment by jaypipes** [comment]
I agree that the `beta.kubernetes.io/os: linux` annotation is deprecated, however please keep in mind the version of the CNI does not correspond to the version of Kubernetes being targeted. Because we don't know which version of Kubernetes the CNI plugin is being installed in, it is safer to have both the deprecated beta and non-beta current annotation in a nodeAffinity selector and use an OR strategy like so:

```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                 # Remove this match expression when we're sure the CNI isn't
                 # installed anywhere that uses kubelet's that label Node objects
                 # with the deprecated beta label...
                  - key: "beta.kubernetes.io/os"
                    operator: In
                    values:
                      - linux
                  - key: "beta.kubernetes.io/arch"
                    operator: In
                    values:
                      - amd64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
              - matchExpressions:
                  - key: "kubernetes.io/os"
                    operator: In
                    values:
                      - linux
                  - key: "beta.kubernetes.io/arch"
                    operator: In
                    values:
                      - amd64
                  - key: eks.amazonaws.com/compute-type
                    operator: NotIn
                    values:
                      - fargate
```

I believe both the `calico.yaml` and the `aws-k8s-cni.yaml` files in the config directories should be updated to the above and be consistent. I would welcome a pull request from you that made the above change, @Gmagella! :)
