### ISSUE TITLE
Is dockersock mount still needed?

### ISSUE THREAD

**Issue by moensch** [aws/amazon-vpc-cni-k8s#971]
I am running `containerd` on my hosts, provisioned via https://github.com/kubernetes-sigs/cluster-api-provider-aws (k8s 1.17.x) and my hosts don't run docker.

I noticed the `DaemonSet` still has these two volume mounts in both, the release YAML and the helm chart:
```yaml
            - mountPath: /var/run/docker.sock
              name: dockersock
            - mountPath: /var/run/dockershim.sock
              name: dockershim
```

I found a merged PR that, as I understand it, made this project runtime agnostic: https://github.com/aws/amazon-vpc-cni-k8s/pull/371

With that in mind, is this socket mount still needed? I ask because on systems running `containerd` it does not exist.
