### ISSUE TITLE
CNI doesn't work on m5c.metal

### ISSUE THREAD

**Issue by nucleusv** [aws/amazon-vpc-cni-k8s#999]
CNI plugin does not work on bare metal instance.
m5c.metal - nodegroup is created by eksctl.

EKS version: 1.16 
CNI version: v1.6.1

/var/log/messages
May 28 10:14:34 ip-10-139-5-46 kubelet: E0528 10:14:34.558084   12242 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
May 28 10:14:38 ip-10-139-5-46 kubelet: W0528 10:14:38.533606   12242 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
May 28 10:14:39 ip-10-139-5-46 kubelet: E0528 10:14:39.558456   12242 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
May 28 10:14:43 ip-10-139-5-46 kubelet: W0528 10:14:43.533685   12242 cni.go:237] Unable to update cni config: no networks found in /etc/cni/net.d
May 28 10:14:44 ip-10-139-5-46 kubelet: E0528 10:14:44.558789   12242 kubelet.go:2192] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized

**Comment by mogren** [comment]
Hi @nucleusv,

What instance type were you saying that you used? I tried creating a 1.16 cluster using `m5.metal` nodes:
```
> eksctl create cluster -r us-west-2 -n metal-cluster -t m5.metal -N 2 --version 1.16 --managed --ssh-access
```
That gave me a cluster with two nodes that I could ssh into. Checking the type:
```
$ curl http://169.254.169.254/latest/meta-data/instance-type
m5.metal
```
I scheduled 300 pods on those two nodes and they came up fine:
```
> kubectl get pods | grep Running | wc -l
     300
```

Checking the [list of m5](https://aws.amazon.com/ec2/instance-types/m5/) instance types, did you mean `m5d.metal`?

**Comment by nucleusv** [comment]
@mogren sorry for confusion, actually it was c5.metal

```
nga1-windows-baremetal-1-1c
    availabilityZones: ["eu-west-1c"]
    amiFamily: AmazonLinux2
    instanceType: c5.metal
    minSize: 1
    maxSize: 2
    volumeSize: 20
    volumeType: gp2
    privateNetworking: true
    securityGroups:
      withShared: true
      withLocal: true
....
```
